/*******************************************************************************************************************************************
 * File Name: sp_wt_qc_SampleUpdate.sql
 * Project: smashbox
 * Description: 
 * Notes:
 * =========================================================================================================================================
 * Change Log ([MM/DD/YYYY]|[Developer]|[Task Ticket] - [Description]
 * =========================================================================================================================================
 * 01/26/2018|mnutsch|KACE:xxxxx - Initial creation
 * 01/26/2018|mnutsch|KACE:20305 - Added Near Size parameter.
 * 
 ******************************************************************************************************************************************/


DROP PROCEDURE IF EXISTS sp_wt_qc_SampleUpdate;

DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE sp_wt_qc_SampleUpdate
(
    IN p_id INT(11),
    IN p_edit_dt DATETIME,
    IN p_edit_user_id BIGINT(20), 
    IN p_site_id INT(11),
    IN p_plant_id INT(11),
    IN p_dt DATETIME,
    IN p_test_type_id INT(11),
    IN p_composite_type_id INT(11),
    IN p_sieve_method_id INT(11),
    IN p_location_id INT(11),
    IN p_specific_location_id INT(11),
    IN p_date DATE,
    IN p_time TIME,
    IN p_date_short BIGINT(8),
    IN p_dt_short BIGINT(11),
    IN p_oversize_percent DECIMAL(5, 4),
    IN p_oversize_weight DECIMAL(5, 1),
    IN p_slimes_percent DECIMAL(5, 4),
    IN p_depth_to DECIMAL(5, 1),
    IN p_depth_from DECIMAL(5, 1),
    IN p_drillhole_no VARCHAR(50),
    IN p_description VARCHAR(50),
    IN p_sampler VARCHAR(32),
    IN p_lab_tech VARCHAR(32),
    IN p_operator VARCHAR(32),
    IN p_beginning_wet_weight DECIMAL(5, 1),
    IN p_prewash_dry_weight DECIMAL(5, 1),
    IN p_postwash_dry_weight DECIMAL(5, 1),
    IN p_split_sample_weight DECIMAL(5, 1),
    IN p_moisture_rate DECIMAL(6, 4),
    IN p_notes VARCHAR(255),
    IN p_turbidity INT(11),
    IN p_k_value INT(11),
    IN p_k_pan_1 DECIMAL(7, 4),
    IN p_k_pan_2 DECIMAL(7, 4),
    IN p_k_pan_3 DECIMAL(7, 4),
    IN p_roundness DECIMAL(5, 1),
    IN p_sphericity DECIMAL(5, 1),
    IN p_group_time TIME,
    IN p_start_weights_raw TEXT,
    IN p_end_weights_raw TEXT,
    IN p_sieves_raw TEXT,
    IN p_sieves_total DECIMAL(5, 1),
    IN p_sieve_1_value DECIMAL(7, 4),
    IN p_sieve_2_value DECIMAL(7, 4),
    IN p_sieve_3_value DECIMAL(7, 4),
    IN p_sieve_4_value DECIMAL(7, 4),
    IN p_sieve_5_value DECIMAL(7, 4),
    IN p_sieve_6_value DECIMAL(7, 4),
    IN p_sieve_7_value DECIMAL(7, 4),
    IN p_sieve_8_value DECIMAL(7, 4),
    IN p_sieve_9_value DECIMAL(7, 4),
    IN p_sieve_10_value DECIMAL(7, 4),
    IN p_sieve_11_value DECIMAL(7, 4),
    IN p_sieve_12_value DECIMAL(7, 4),
    IN p_sieve_13_value DECIMAL(7, 4),
    IN p_sieve_14_value DECIMAL(7, 4),
    IN p_sieve_15_value DECIMAL(7, 4),
    IN p_sieve_16_value DECIMAL(7, 4),
    IN p_sieve_17_value DECIMAL(7, 4),
    IN p_sieve_18_value DECIMAL(7, 4),
    IN p_sieve_1_desc CHAR(3),
    IN p_sieve_2_desc CHAR(3),
    IN p_sieve_3_desc CHAR(3),
    IN p_sieve_4_desc CHAR(3),
    IN p_sieve_5_desc CHAR(3),
    IN p_sieve_6_desc CHAR(3),
    IN p_sieve_7_desc CHAR(3),
    IN p_sieve_8_desc CHAR(3),
    IN p_sieve_9_desc CHAR(3),
    IN p_sieve_10_desc CHAR(3),
    IN p_sieve_11_desc CHAR(3),
    IN p_sieve_12_desc CHAR(3),
    IN p_sieve_13_desc CHAR(3),
    IN p_sieve_14_desc CHAR(3),
    IN p_sieve_15_desc CHAR(3),
    IN p_sieve_16_desc CHAR(3),
    IN p_sieve_17_desc CHAR(3),
    IN p_sieve_18_desc CHAR(3),
    IN p_plus_70 DECIMAL(5, 4),
    IN p_minus_40_plus_70 DECIMAL(5, 4),
    IN p_minus_70 DECIMAL(5, 4),
    IN p_minus_70_plus_140 DECIMAL(5, 4),
    IN p_minus_140 DECIMAL(5, 4),
    IN p_finish_dt DATETIME,
    IN p_duration DECIMAL(5, 2),
    IN p_duration_minutes DECIMAL(5, 1),
    IN p_is_coa TINYINT(1),
    IN p_near_size DECIMAL(5, 4)
)
BEGIN
UPDATE wt_qc_samples
    SET 
        edit_dt = p_edit_dt,
        edit_user_id = p_edit_user_id, 
        site_id = p_site_id,
        plant_id = p_plant_id,
        dt = p_dt,
        test_type_id = p_test_type_id,
        composite_type_id = p_composite_type_id,
        sieve_method_id = p_sieve_method_id,
        location_id = p_location_id,
        specific_location_id = p_specific_location_id, 
        date = p_date,
        time = p_time,
        date_short = p_date_short,
        dt_short = p_dt_short,
        oversize_percent = p_oversize_percent, 
        oversize_weight = p_oversize_weight, 
        slimes_percent = p_slimes_percent, 
        depth_to = p_depth_to, 
        depth_from = p_depth_from, 
        drillhole_no = p_drillhole_no,
        description = p_description,
        sampler = p_sampler,
        lab_tech = p_lab_tech,
        operator = p_operator,
        beginning_wet_weight = p_beginning_wet_weight,
        prewash_dry_weight = p_prewash_dry_weight,
        postwash_dry_weight = p_postwash_dry_weight,
        split_sample_weight = p_split_sample_weight,
        moisture_rate = p_moisture_rate,
        notes = p_notes,
        turbidity = p_turbidity,
        k_value = p_k_value,
        k_pan_1 = p_k_pan_1,
        k_pan_2 = p_k_pan_2,
        k_pan_3 = p_k_pan_3,
        roundness = p_roundness,
        sphericity = p_sphericity,
        group_time = p_group_time,
        start_weights_raw = p_start_weights_raw,
        end_weights_raw = p_end_weights_raw,
        sieves_raw = p_sieves_raw,
        sieves_total = p_sieves_total, 
        sieve_1_value = p_sieve_1_value, 
        sieve_2_value = p_sieve_2_value, 
        sieve_3_value = p_sieve_3_value, 
        sieve_4_value = p_sieve_4_value, 
        sieve_5_value = p_sieve_5_value, 
        sieve_6_value = p_sieve_6_value, 
        sieve_7_value = p_sieve_7_value, 
        sieve_8_value = p_sieve_8_value, 
        sieve_9_value = p_sieve_9_value, 
        sieve_10_value = p_sieve_10_value, 
        sieve_11_value = p_sieve_11_value, 
        sieve_12_value = p_sieve_12_value, 
        sieve_13_value = p_sieve_13_value, 
        sieve_14_value = p_sieve_14_value, 
        sieve_15_value = p_sieve_15_value, 
        sieve_16_value = p_sieve_16_value, 
        sieve_17_value = p_sieve_17_value, 
        sieve_18_value = p_sieve_18_value, 
        sieve_1_desc = p_sieve_1_desc,
        sieve_2_desc = p_sieve_2_desc,
        sieve_3_desc = p_sieve_3_desc,
        sieve_4_desc = p_sieve_4_desc,
        sieve_5_desc = p_sieve_5_desc,
        sieve_6_desc = p_sieve_6_desc,
        sieve_7_desc = p_sieve_7_desc,
        sieve_8_desc = p_sieve_8_desc,
        sieve_9_desc = p_sieve_9_desc,
        sieve_10_desc = p_sieve_10_desc,
        sieve_11_desc = p_sieve_11_desc,
        sieve_12_desc = p_sieve_12_desc,
        sieve_13_desc = p_sieve_13_desc,
        sieve_14_desc = p_sieve_14_desc,
        sieve_15_desc = p_sieve_15_desc,
        sieve_16_desc = p_sieve_16_desc,
        sieve_17_desc = p_sieve_17_desc,
        sieve_18_desc = p_sieve_18_desc,        
        plus_70 = p_plus_70, 
        minus_40_plus_70 = p_minus_40_plus_70, 
        minus_70 = p_minus_70, 
        minus_70_plus_140 = p_minus_70_plus_140, 
        minus_140 = p_minus_140, 
        finish_dt = p_finish_dt, 
        duration = p_duration, 
        duration_minutes = p_duration_minutes,
        is_coa = p_is_coa,
        near_size = p_near_size
    WHERE id = p_id;
END$$

DELIMITER ;

