
/*******************************************************************************************************************************************
 * File Name: sp_gb_plc_SilosInsert.sql
 * Project: silicore
 * Description:
 * Notes:
 * =========================================================================================================================================
 * Change Log ([MM/DD/YYYY]|[Developer]|[Task Ticket] - [Description])
 * =========================================================================================================================================
 * 10/30/2017|whildebrandt|KACE:16787 - Insert data for prod_silos
 *
 ******************************************************************************************************************************************/
# Insert data for prod_silos

INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('1', '1', '10', NULL, '650377', '650377', '125000', NULL, '1', '0', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('2', '2', '10', NULL, '2299320', '2299320', '200000', NULL, '1', '2', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('3', '3', '10', NULL, '250000', '250000', '0', NULL, '1', '4', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('4', '4', '10', NULL, '250000', '250000', '0', NULL, '1', '6', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('5', '5', '10', NULL, '250000', '250000', '0', NULL, '1', '8', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('6', '6', '10', NULL, '3056670', '3056670', '550000', NULL, '1', '10', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('7', '7', '10', NULL, '3056670', '3056670', '550000', NULL, '1', '12', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('8', 'A1', '20', '50.0', '1075000', '1075000', '75000', '20000', '1', '200', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('9', 'A2', '20', '50.0', '1075000', '1075000', '75000', '20000', '1', '205', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('10', 'A3', '20', '50.0', '1075000', '1075000', '75000', '20000', '1', '210', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('11', 'A4', '20', '50.0', '1075000', '1075000', '75000', '20000', '1', '215', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('12', 'A5', '20', '50.0', '1075000', '1075000', '75000', '20000', '1', '220', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('13', 'A6', '20', '50.0', '1075000', '1075000', '75000', '20000', '1', '225', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('14', 'B1', '20', '50.0', '1075000', '1075000', '75000', '20000', '1', '230', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('15', 'B2', '20', '50.0', '1075000', '1075000', '75000', '20000', '1', '235', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('16', 'B3', '20', '50.0', '1075000', '1075000', '75000', '20000', '1', '240', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('17', 'B4', '20', '50.0', '1075000', '1075000', '75000', '20000', '1', '245', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('18', 'B5', '20', '50.0', '1075000', '1075000', '75000', '20000', '1', '250', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('19', 'B6', '20', '50.0', '1075000', '1075000', '75000', '20000', '1', '255', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('20', 'Ground', '10', NULL, NULL, NULL, '0', NULL, '0', '95', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('21', 'Ground', '20', NULL, NULL, NULL, '0', NULL, '0', '260', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('22', 'Unk-Cust', '999', NULL, NULL, NULL, '0', NULL, '0', '999', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('23', 'Unk-Maalt(N)', '11', NULL, NULL, NULL, '0', NULL, '0', '18', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('24', 'Unk-Maalt(S)', '12', NULL, NULL, NULL, '0', NULL, '0', '18', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('25', 'Unk-Maalt(Cle)', '13', NULL, NULL, NULL, '0', NULL, '0', '18', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('26', 'Ground', '30', NULL, NULL, NULL, '0', NULL, '0', '300', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('27', 'UFR', '10', NULL, NULL, NULL, '0', NULL, '0', '90', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('28', 'Ground-Momentive', '210', NULL, NULL, NULL, '0', NULL, '0', '100', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('29', 'RailSilo', '20', NULL, NULL, NULL, '0', NULL, '1', '265', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('30', '8', '10', NULL, '3056670', '3056670', '550000', NULL, '1', '20', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('31', '9', '10', NULL, '3056670', '3056670', '550000', NULL, '1', '25', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('32', 'Unk-Tidewater(SA)', '700', NULL, NULL, NULL, '0', NULL, '0', '700', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('33', 'Unk-Maalt(BL)', '25', NULL, NULL, NULL, '0', NULL, '0', '18', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('34', 'Unk-Maalt(EN)', '16', NULL, NULL, NULL, '0', NULL, '0', '18', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('35', 'Unk-Maalt(BS)', '15', NULL, NULL, NULL, '0', NULL, '0', '18', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('36', 'Unk-Maalt(GD)', '14', NULL, NULL, NULL, '0', NULL, '0', '18', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('37', 'Unk-Maalt(SW)', '17', NULL, NULL, NULL, '0', NULL, '0', '18', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('38', 'Unk-Maalt(Dil)', '18', NULL, NULL, NULL, '0', NULL, '0', '18', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('39', 'Unk-Maalt(Pec)', '19', NULL, NULL, NULL, '0', NULL, '0', '18', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('40', 'Unk-Pinnacle(SA)', '701', NULL, NULL, NULL, '0', NULL, '0', '701', '0');
INSERT INTO `silicore_site`.`prod_silos` (`id`, `description`, `site_id`, `cylinder_feet`, `total_pounds`, `capacity_pounds`, `cone_pounds`, `feet_pounds_factor`, `is_silo`, `sort_order`, `is_removed`) VALUES ('41', 'Unk-Maalt(BH)', '26', NULL, NULL, NULL, '0', NULL, '0', '18', '0');



