
/*******************************************************************************************************************************************
 * File Name: sp_gb_plc_ProdCustomersInsert.sql
 * Project: silicore
 * Description:
 * Notes:
 * =========================================================================================================================================
 * Change Log ([MM/DD/YYYY]|[Developer]|[Task Ticket] - [Description])
 * =========================================================================================================================================
 * 11/01/2017|whildebrandt|KACE:16787 - Insert data for prod_products_customers
 *
 ******************************************************************************************************************************************/

INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('1', '3', NULL, '102055557', 'SAND 20/40 MESH - LB');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('2', '3', NULL, '102045259', 'SAND GRADE 16/30 MESH');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('3', '3', NULL, '102045261', 'PROP,CARBO HYDROPROP, 3000 LB SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('4', '3', NULL, '102076642', 'SINTERLITE RESINADO 12/18, 100 LB SK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('5', '3', NULL, '102076643', 'SINTERLITE RESINADO 12/18, 45.4 KG SK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('6', '3', NULL, '102024283', 'XRT CERAMAX P PT 30/50, 4000 LB SUPER SK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('7', '3', NULL, '102026818', 'CHEM,FORES PROPPANT MPP20/40-1000 KG SK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('8', '3', NULL, '100001588', 'Sand-Premium White ReS-20/40,100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('9', '3', NULL, '100001589', 'Sand-Premium White ReS-40/60,100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('10', '3', NULL, '100002160', 'Sand - Standard - 12/20, 100 lb sk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('11', '3', NULL, '100002159', 'Sand-Premium White-20/40, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('12', '3', NULL, '100003628', 'Sand-Premium Brown-20/40, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('13', '3', NULL, '100003673', 'Sand - Standard -12/20, bulk sk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('14', '3', '9', '100003678', 'Sand-Premium White-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('15', '3', NULL, '100003698', 'Sand-Premium White-16/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('16', '3', NULL, '100003795', 'Sand-Premium Brown-20/40, 50 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('17', '3', NULL, '100003674', 'Sand-Premium Brown-16/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('18', '3', NULL, '100003675', 'Sand-Premium Brown-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('19', '3', '1', '100003676', 'Sand-Common White-100 Mesh, SSA-2, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('20', '3', NULL, '100003677', 'Sand - Premium - 12/20, bulk sk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('21', '3', NULL, '100013011', 'Sand-Premium Brown-30/70, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('22', '3', NULL, '101480115', 'SAND-CRC LT-16/30, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('23', '3', NULL, '100012263', 'Sand - Standard - 12/20, 50 lb sk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('24', '3', NULL, '100012203', 'Sand - Standard - 8/16, bulk sk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('25', '3', NULL, '101246994', 'Sand-Premium Brown-20/40, 4000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('26', '3', NULL, '101495496', 'Sand-CRC-20/40, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('27', '3', NULL, '101499939', 'PROP,FORES, RC CERAMIC,12/18,1000 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('28', '3', NULL, '101252548', 'Sand-Premium White ReS-40/60,4000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('29', '3', NULL, '101500626', 'PROP, PREMIUM PLUS-35/70, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('30', '3', NULL, '101503500', 'SAND, PRC-30/50,  BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('31', '3', NULL, '101506165', 'PROP, ST GOBAIN-12/18, 1000 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('32', '3', NULL, '101507128', 'Sand-Premium White ReS-40/60,2200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('33', '3', NULL, '101507555', 'PROP-PREMIUM-16/30, BULK BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('34', '3', NULL, '101507558', 'PROP-PREMIUM-20/40, BULK BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('35', '3', NULL, '101507562', 'Prop-HSP TA-16/30, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('36', '3', NULL, '101507564', 'Prop-HSP TB-16/30, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('37', '3', NULL, '101507565', 'Prop-HSP TC-16/30, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('38', '3', NULL, '101269974', 'Sand-Premium White ReS-40/60, 25 Kg sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('39', '3', NULL, '101269981', 'Sand-Premium White ReS-40/60, 50 Kg sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('40', '3', NULL, '101269982', 'Sand-Premium White ReS-40/60,2000 Kg bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('41', '3', NULL, '101270510', 'Sand-Premium White ReS-30/50, 50 Kg sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('42', '3', NULL, '101270508', 'Sand-Premium White ReS-30/50, 25 Kg sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('43', '3', NULL, '101270513', 'Sand-Premium White ReS-30/50,2000 Kg bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('44', '3', NULL, '101511497', 'Sand-CRC Premium-16/30, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('45', '3', NULL, '101513727', 'SAND, CHELFORD 20/40 ASTM, 1.5 TON BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('46', '3', NULL, '101513728', 'SAND, CHELFORD 20/40 ASTM, 25 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('47', '3', NULL, '101514094', 'PROP, PREMIUM 70/140, 3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('48', '3', NULL, '101514389', 'Sand-Premium White ReS-16/30,2 Ton(m)Bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('49', '3', NULL, '100063972', 'Sand-Premium White ReS-16/30,100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('50', '3', NULL, '100064002', 'Sand - Standard -10/20, bulk sk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('51', '3', '2', '100064018', 'Sand-Premium White-40/70, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('52', '3', NULL, '100064055', 'Sand-Common Brown-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('53', '3', NULL, '100064058', 'Sand-Common Brown-12/20, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('54', '3', NULL, '100064104', 'Sand-Premium Brown-20/40, 3000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('55', '3', NULL, '100064142', 'Sand-Premium White ReS-50/70,3000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('56', '3', NULL, '100064171', 'Sand-Premium White-16/30, 3000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('57', '3', NULL, '100064256', 'Sand-Premium White ReS-30/40, 50lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('58', '3', NULL, '100064258', 'Sand-Premium White ReS-50/70, 50 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('59', '3', NULL, '100064056', 'Sand-Common Brown-40/70, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('60', '3', NULL, '100064057', 'Sand - Standard - 10/20, bulk sk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('61', '3', NULL, '100064108', 'Sand-Premium White-16/30, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('62', '3', NULL, '100064132', 'Sand-Common Brown-16/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('63', '3', NULL, '100064133', 'Sand-Premium Brown-12/20, 3000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('64', '3', NULL, '100064140', 'Sand-Premium White ReS-20/40,3000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('65', '3', NULL, '100064141', 'Sand-Premium White ReS-40/60,3000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('66', '3', NULL, '100064152', 'Sand - Standard - 8/12, 3000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('67', '3', NULL, '100064162', 'Sand-Premium White-20/40, 3000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('68', '3', NULL, '100064163', 'Sand - Premium - 12/20, 3000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('69', '3', NULL, '100064235', 'Sand - Standard - 10/40, bulk sk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('70', '3', NULL, '100064257', 'PROP, CERAMIC-30/50, 50 LB SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('71', '3', NULL, '101272868', 'Sand-CRC Premium-20/40, 25 Kg sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('72', '3', NULL, '101272869', 'Sand-CRC Premium-20/40, 50 Kg sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('73', '3', NULL, '101272870', 'Sand-CRC Premium-20/40, 2000 Kg bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('74', '3', NULL, '101272933', 'Sand-Common White-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('75', '3', NULL, '101519791', 'PROP,FORES, RC CERAMIC,16/20,1000 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('76', '3', NULL, '101523710', 'PROP, PROP+ HL - 20/40, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('77', '3', NULL, '101523712', 'PROP, PROP+ HL - 16/30, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('78', '3', NULL, '101523714', 'PROP, PROP+ HL - 12/20, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('79', '3', NULL, '101537046', 'Sand,Premium White ReS,20/40,1000 kg bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('80', '3', NULL, '101540425', 'PROP,FORES, RC CERAMIC, 6/10,1000 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('81', '3', NULL, '100023176', 'Glass Beads-Coarse, 50 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('82', '3', NULL, '100023186', 'Sand-Premium White ReS-12/20,100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('83', '3', NULL, '101228353', 'Sand-Premium White ReS-12/20,3000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('84', '3', NULL, '101228354', 'Sand-Premium White ReS-16/30,3000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('85', '3', NULL, '101228355', 'Sand-Premium Brown-30/70, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('86', '3', NULL, '101279715', 'Prop-Ceramic-30/50 QP-EUF-CEP30_50');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('87', '3', NULL, '101549430', 'PROP,FORES, PREMIUM,16/20,1000 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('88', '3', NULL, '101550766', 'PROP, THERMAPAC 20/40, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('89', '3', NULL, '101553313', 'SAND, PRC PREMIUM WHITE, 30/50, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('90', '3', NULL, '101553321', 'Sand-Premium White ReS-40/60, 50 Lb Sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('91', '3', NULL, '101553322', 'Sand-Premium White ReS-20/40, 50 Lb Sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('92', '3', NULL, '101553323', 'Prop-Prem Plus-30/50, 30/60, 3300 Lb Bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('93', '3', NULL, '101229881', 'Sand- 90 MESH (3,000# Bag)');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('94', '3', NULL, '101562751', 'SYNTHETIC ROCK CORE');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('95', '3', NULL, '101564783', 'Prop-35/140 Premium, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('96', '3', NULL, '101232490', 'Sand - Standard - 10/40, 3000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('97', '3', NULL, '101574480', 'SAND, COMMON WHITE - 90 MESH, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('98', '3', NULL, '101587161', 'PROP, CERAMIC-40/70, 3200 LB  BULK BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('99', '3', NULL, '101588141', 'SAND, CRC-30/50, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('100', '3', NULL, '101588616', 'PROP, SINTER BLAST 60/120, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('101', '3', NULL, '101591917', 'Sand-CRC Premium-20/40, 3200 Lb Bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('102', '3', NULL, '101597146', 'PROP, SUPER HS BAUXITE 20/40,3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('103', '3', NULL, '101598322', 'PROP, ISIGRAVA 2-4');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('104', '3', NULL, '101598323', 'PROP, SINTERBALL-30/50, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('105', '3', NULL, '101598812', 'PROP, BORO PRECURED RC - 12/18, 1000 KG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('106', '3', NULL, '101600623', 'PROP, BORO PRECURED RC - 16/20, 1000 KG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('107', '3', NULL, '101605597', 'SAND-PREMIUM WHITE-20/40, 2000 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('108', '3', NULL, '101297475', 'Prop-Ceramic-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('109', '3', NULL, '101297491', 'Prop-Ceramic-20/40, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('110', '3', NULL, '101297495', 'Prop-Ceramic-30/50, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('111', '3', NULL, '101297497', 'Prop-Ceramic Plus-12/18, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('112', '3', NULL, '101297503', 'Prop-Ceramic Plus-16/20, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('113', '3', NULL, '101297533', 'Prop-Ceramic Plus-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('114', '3', NULL, '101297535', 'Prop-Ceramic Plus-20/40, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('115', '3', NULL, '101297536', 'Prop-Premium-12/20, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('116', '3', NULL, '101297539', 'Prop-Premium-16/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('117', '3', NULL, '101297540', 'Prop-Premium-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('118', '3', NULL, '101297541', 'Prop-Ceramic-20/40, 50 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('119', '3', NULL, '101297555', 'Prop-Ceramic Plus-12/18, 25 Kg sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('120', '3', NULL, '101297556', 'Prop-Premium-16/30, 1300 Kg bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('121', '3', NULL, '101297557', 'Prop-Ceramic Plus-16/20, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('122', '3', NULL, '101297558', 'Prop-Premium-16/30, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('123', '3', NULL, '101297612', 'Prop-Ceramic Plus-20/40, 50 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('124', '3', NULL, '101297613', 'Prop-Premium-20/40, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('125', '3', NULL, '101297614', 'Prop-Premium-30/60, 50 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('126', '3', NULL, '101297615', 'Prop-Premium-30/50,30/60, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('127', '3', NULL, '101297616', 'Prop-Premium Plus-12/20, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('128', '3', NULL, '101297617', 'Prop-Premium Plus-12/20, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('129', '3', NULL, '101297618', 'Prop-Premium Plus-16/30, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('130', '3', NULL, '101297619', 'Prop-16/30,16/20 Premium Plus - Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('131', '3', NULL, '101297653', 'Prop-Premium Plus-18/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('132', '3', NULL, '101297656', 'Prop-Premium Plus-20/40, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('133', '3', NULL, '101297659', 'Prop-Premium Plus-20/40, 50 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('134', '3', NULL, '101297663', 'Prop-Premium Plus-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('135', '3', NULL, '101297664', 'Prop-Prem Plus-30/50,30/60,3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('136', '3', NULL, '101297667', 'Prop-Premium Plus-30/50,30/60, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('137', '3', NULL, '101297668', 'Prop-Premium Plus-40/70 40/80, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('138', '3', NULL, '101297669', 'Prop-RC Ceramic-16/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('139', '3', NULL, '101297672', 'Prop-RC Ceramic-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('140', '3', NULL, '101297674', 'Prop-RC Ceramic Plus-16/20, 3800 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('141', '3', NULL, '101297677', 'Prop-RC Ceramic Plus-16/20, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('142', '3', NULL, '101297700', 'Prop-RC Ceramic Plus-20/40, Bulk Bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('143', '3', NULL, '101297701', 'Prop-RC Ceramic Plus-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('144', '3', NULL, '101297702', 'Prop-RC Premium Plus-16/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('145', '3', NULL, '101297703', 'Prop-RC Premium Plus-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('146', '3', NULL, '101297704', 'Prop-RC Premium Plus-30/50,30/60, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('147', '3', NULL, '101615075', 'PROP-CERAMIC PLUS-16/30, 3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('148', '3', NULL, '101618879', 'SAND,COM WHITE-100 MESH,SSA-2,1500 KG BG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('149', '3', NULL, '101620712', 'PROP, 35/140 PREMIUM, 3200 LB BULK BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('150', '3', NULL, '101622811', 'SAND, COMMON WHITE-20/60');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('151', '3', NULL, '101623870', 'SAND, CRC PREMIUM PLUS-20/40,2000 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('152', '3', NULL, '101625916', 'SAND, PREMIUM BROWN-30/50, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('153', '3', NULL, '100090992', 'Sand-Premium Plus White-20/40');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('154', '3', NULL, '101632600', 'PROP, CARBO ACCUCAST LD-60');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('155', '3', NULL, '100090995', 'Sand-Premium Plus White-16/30');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('156', '3', NULL, '101634414', 'SAND,COM WHITE-100 MESH, SSA-2, 25 KG SK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('157', '3', NULL, '101634416', 'SAND, COMMON BROWN-40/70, 25 KG SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('158', '3', NULL, '101634415', 'SAND, PREMIUM WHITE RES-12/20, 25 KG SK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('159', '3', NULL, '101634418', 'SAND, PREMIUM WHITE-16/30, 25 KG SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('160', '3', NULL, '101634417', 'SAND, PREMIUM BROWN-20/40, 25 KG SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('161', '3', NULL, '101634419', 'SAND, PREMIUM WHITE-20/40, 25 KG SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('162', '3', NULL, '101634420', 'SAND, PREMIUM WHITE RES-20/40, 25 KG SK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('163', '3', NULL, '101634421', 'SAND, PREMIUM WHITE RES-40/60, 25 KG SK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('164', '3', NULL, '101634422', 'SAND, PREMIUM WHITE RES-50/70, 25 KG SAC');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('165', '3', NULL, '101634423', 'SAND, PREMIUM WHITE-12/20, 25 KG SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('166', '3', NULL, '101303229', 'Prop-Premium-20/40, 1000 Kg bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('167', '3', NULL, '101303486', 'Prop-RC Ceramic Plus-16/20, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('168', '3', NULL, '101303325', 'Prop-Ceramax XRT-P-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('169', '3', NULL, '101303230', 'Prop-Premium-16/30, 1000 Kg bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('170', '3', NULL, '101303538', 'Prop-Premium-20/40, 25 Kg sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('171', '3', NULL, '101645741', 'PROP-RC PREMIUM-12/18, 1000 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('172', '3', NULL, '101645743', 'PROP-RC PREMIUM-16/20, 1000 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('173', '3', NULL, '101645742', 'PROP-RC PREMIUM-10/14, 1000 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('174', '3', NULL, '101645324', 'PROP,ULTRAPROP SINTERED BAUXITE,BULK BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('175', '3', NULL, '101649541', 'PROP, CARBO HYDROPROP, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('176', '3', NULL, '101649542', 'PROP, CARBO ACCUCAST LD-50');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('177', '3', NULL, '101305327', 'Prop-RC Premium Plus-16/30, 4500 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('178', '3', NULL, '101655221', 'PROP, VERSAPROP, BULK BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('179', '3', NULL, '101658104', 'PROP, CERAMIC PLUS - 16/30, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('180', '3', NULL, '101658105', 'PROP, CERAMIC PLUS - 30/50, 30/60, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('181', '3', NULL, '101658111', 'PROP, PREMIUM - 12/18, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('182', '3', NULL, '101658128', 'SAND, RESIN SAND 20/40, 1 TON BIG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('183', '3', NULL, '101658130', 'SAND, RESIN SAND 12/20, 1 TON BIG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('184', '3', NULL, '101658129', 'SAND, RESIN SAND 16/30, 1 TON BIG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('185', '3', NULL, '101305532', 'Prop-RC Premium Plus-16/30, 3800 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('186', '3', NULL, '101667548', 'SAND, 12/20 CR 3000 PSI, 2200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('187', '3', NULL, '101669745', 'PROP, MONOPROP, 1000 LB SUPERSACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('188', '3', NULL, '101669746', 'PROP, MONOPROP, 5000 LB SUPERSACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('189', '3', NULL, '101310461', 'Prop-Versaprop, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('190', '3', NULL, '101312772', 'Prop-RC Ceramic Plus-12/18, 3800 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('191', '3', NULL, '101313232', 'Prop-Premium-16/20, 1000 Kg bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('192', '3', NULL, '101312915', 'Sand-Common Brown 100 Mesh, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('193', '3', NULL, '101682581', 'SAND DUMP, 20/40 MESH, 2200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('194', '3', NULL, '101687839', 'PROP, SINTER BLAST 60/120, 50 LB SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('195', '3', NULL, '101687840', 'PROP, SINTER BLAST 60/120, 2200 LB SUPER');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('196', '3', NULL, '101315014', 'Prop-Premium-12/20, 1000 Kg bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('197', '3', NULL, '101689406', 'PROP-PREMIUM-30/50, 3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('198', '3', NULL, '101695027', 'PROP - HORIZON?, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('199', '3', NULL, '101695028', 'PROP - HORIZON?, 100 LB SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('200', '3', NULL, '101702139', 'SAND - PREMIUM BROWN- 16/30, 2645 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('201', '3', NULL, '101702140', 'SAND - PREMIUM BROWN- 16/30, 3307 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('202', '3', NULL, '101702145', 'SAND - PREMIUM BROWN-20/40, 2645 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('203', '3', NULL, '101702146', 'SAND - PREMIUM BROWN-20/40, 3307 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('204', '3', NULL, '101702182', 'SAND - COMMON WHITE 100 MESH, 2645 LB BA');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('205', '3', NULL, '101702183', 'SAND - COMMON WHITE 100 MESH, 3307 LB BA');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('206', '3', NULL, '101706811', 'PROP, PREMIUM 16/50, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('207', '3', NULL, '101213213', 'Sand-Premium White ReS-20/40,4000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('208', '3', NULL, '101714015', 'PROP,FORES, PREMIUM,12/18,1000 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('209', '3', NULL, '101717526', 'PROP, CARBOPROP 12/18, 1500 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('210', '3', NULL, '101734839', 'SAND, COMMON WHITE - 20/45, BULK (METRIC');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('211', '3', NULL, '101734840', 'PROP, SINTERLITE LOCK 16/30, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('212', '3', NULL, '101734841', 'PROP, SINTERLITE LOCK 20/40, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('213', '3', NULL, '101741481', 'SAND, GGL G2-20/40 , BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('214', '3', NULL, '101744121', 'SAND-COM WHITE-100 MESH,SSA-2, 2000 LB');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('215', '3', NULL, '101318349', 'Prop-Premium-40/70, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('216', '3', NULL, '101753625', 'PROP, SINTER BLAST 40/120, 3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('217', '3', NULL, '101759854', 'Prop-RC Premium-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('218', '3', NULL, '101761150', 'Deleted Sand-CRC Premium Plus-16/40,Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('219', '3', NULL, '101321532', 'Prop-RC Ceramic-30/50, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('220', '3', NULL, '101768814', 'Sand-CRC Premium Plus-16/40, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('221', '3', NULL, '101322513', 'Prop-RC Premium-30/60, 3800 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('222', '3', NULL, '101322286', 'Prop-Premium Plus-30/50,30/60,50 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('223', '3', NULL, '101322512', 'Prop-RC Premium-30/60, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('224', '3', NULL, '101323275', 'Prop-Premium-40/70, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('225', '3', NULL, '101323194', 'Sand-Premium White ReS-30/50,3000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('226', '3', NULL, '101773160', 'PROP, CARBO-LITE - 12/18, 3307 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('227', '3', NULL, '101775969', 'PROP,CARBOPROP PLUS OPTIPROP 12/18');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('228', '3', NULL, '101327226', 'Sand-Premium Brown-16/30, 3000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('229', '3', NULL, '101226353', 'Sand- 40/60 Ottawa Frac (Bulk)');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('230', '3', NULL, '101238012', 'Prop-Bauxite Super HS-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('231', '3', NULL, '25026', 'BioBalls MR - 7/8 OD - 1.18 S.G.');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('232', '3', NULL, '101784930', 'PROP, VERSALITE, BULK (LBS)');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('233', '3', NULL, '101335328', 'Sand-Com White-100 Mesh,SSA-2,2500 lb bg');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('234', '3', NULL, '101786765', 'PROP, CARBO HYDROPROP 20/50, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('235', '3', NULL, '101240277', 'Sand-Premium White-50/70, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('236', '3', NULL, '101346474', 'Sand-PRC Premium-25/50, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('237', '3', NULL, '101348886', 'Prop-Ceramic-40/70, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('238', '3', NULL, '101350171', 'Sand - Premium - 12/20, kg');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('239', '3', NULL, '101815510', 'PROP, CERAMIC PLUS - 40/80, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('240', '3', NULL, '101351499', 'PROP,PREMIUM-10/14, 1000 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('241', '3', NULL, '101822155', 'SAND, CRC PREMIUM - 30/50, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('242', '3', NULL, '101822785', 'PROP, CERAMIC ABRASIVE 60/120, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('243', '3', NULL, '101351820', 'Sand-CRC LT-12/20, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('244', '3', NULL, '101353183', 'Prop-Sinterball-18/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('245', '3', NULL, '101353572', 'Sand-Premium Brown-12/20, 4000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('246', '3', NULL, '101829046', 'PROP, PREMIUM 40/80, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('247', '3', NULL, '101831423', 'PROP, HSP TD-16/30, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('248', '3', NULL, '101831424', 'PROP, HSP TE-16/30, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('249', '3', NULL, '101357925', 'Sand-PRC-12/20, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('250', '3', NULL, '101357929', 'Sand-PRC Premium-12/20, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('251', '3', NULL, '101357933', 'Sand-PRC Premium-40/70, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('252', '3', NULL, '101357938', 'Sand-CRC-16/30, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('253', '3', NULL, '101357947', 'Sand-CRC-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('254', '3', NULL, '101357957', 'Sand-CRC Premium-12/20, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('255', '3', NULL, '101357961', 'Sand-CRC Premium-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('256', '3', NULL, '101357966', 'Prop-RC Ceramic Plus-16/30, 4000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('257', '3', NULL, '101357973', 'Prop-RC Premium-16/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('258', '3', NULL, '101357927', 'Sand-PRC-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('259', '3', NULL, '101357931', 'Sand-PRC Premium-20/40, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('260', '3', NULL, '101357936', 'Sand-CRC-12/20, 4000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('261', '3', NULL, '101357946', 'Sand-CRC-20/40, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('262', '3', NULL, '101357949', 'Sand-CRC Premium-12/20, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('263', '3', NULL, '101357958', 'Sand-CRC Premium-16/30, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('264', '3', NULL, '101357964', 'Sand-CRC Premium-40/70, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('265', '3', NULL, '101357972', 'Prop-RC Premium-16/30, 4000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('266', '3', NULL, '101357976', 'Prop-Ceramic-16/30, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('267', '3', NULL, '101357926', 'Sand-PRC-16/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('268', '3', NULL, '101357930', 'Sand-PRC Premium-16/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('269', '3', NULL, '101357934', 'Sand-CRC-12/20, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('270', '3', NULL, '101357939', 'Sand-CRC-16/30, 4000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('271', '3', NULL, '101357948', 'Sand-CRC-40/70, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('272', '3', NULL, '101357959', 'Sand-CRC Premium-16/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('273', '3', NULL, '101357963', 'Sand-CRC Premium-25/50, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('274', '3', NULL, '101357967', 'Prop-RC Ceramic Plus-16/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('275', '3', NULL, '101357975', 'Prop-Premium Plus-20/40, 3300 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('276', '3', NULL, '101357928', 'Sand-PRC Premium-12/20, 4000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('277', '3', NULL, '101357932', 'Sand-PRC Premium-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('278', '3', NULL, '101357937', 'Sand-CRC-12/20, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('279', '3', NULL, '101357940', 'Sand-CRC-16/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('280', '3', NULL, '101357950', 'Sand-CRC Premium-12/20, 4000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('281', '3', NULL, '101357960', 'Sand-CRC Premium-20/40, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('282', '3', NULL, '101357965', 'Prop-RC Ceramic Plus-16/30, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('283', '3', NULL, '101357971', 'Prop-RC Premium-16/30, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('284', '3', NULL, '101357977', 'Prop-Ceramic-30/50, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('285', '3', NULL, '101358406', 'Prop-RC Ceramic Plus-16/30, 1000 kg bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('286', '3', NULL, '101840345', 'SAND-CRC PREMIUM PLUS-16/30, 3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('287', '3', NULL, '101359878', 'Sand-PRC-12/20, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('288', '3', NULL, '101360580', 'Sand-PRC-12/20, 4000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('289', '3', NULL, '101360582', 'Sand-PRC-40/70, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('290', '3', '10', '100009377', 'Sand-Premium White-30/50, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('291', '3', NULL, '101847177', 'PROP, POWERPROP 40/70, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('292', '3', NULL, '101847178', 'PROP, POWERPROP 20/40, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('293', '3', NULL, '101364278', 'Sand-Premium Brown-12/20, 4000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('294', '3', NULL, '101364300', 'Prop-Premium-12/18, 1000 kg bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('295', '3', NULL, '101364965', 'Prop-RC Premium Plus-20/40, 3800 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('296', '3', NULL, '101366825', 'Prop-Ultraprop Sintered Bauxite, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('297', '3', NULL, '101367443', 'Sand-CRC Premium Plus-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('298', '3', NULL, '101367446', 'Sand-CRC Premium Plus-16/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('299', '3', NULL, '101367454', 'Sand-CRC LT-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('300', '3', NULL, '380961', 'Sand-Common White-16/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('301', '3', NULL, '100028135', 'Sand-Premium Brown-16/30, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('302', '3', NULL, '100028140', 'Sand - Premium - 12/20, 100 lb sk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('303', '3', NULL, '100028141', 'Sand - Standard -8/16, 100 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('304', '3', NULL, '101369104', 'Sand-CRC Premium Plus-40/70, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('305', '3', NULL, '120100350', 'Gravel 20-40 CARBOLITE');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('306', '3', NULL, '120100156', 'Gravel 16-20 CARBOLITE');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('307', '3', NULL, '120100302', 'Gravel 20-40, RES, RESIN COATED');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('308', '3', NULL, '101370695', 'Prop-RC Premium Plus-14/18, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('309', '3', NULL, '101370699', 'Prop-RC Ultraprop Sintered Bauxite, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('310', '3', NULL, '101371422', 'Prop-Premium, 12/18, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('311', '3', NULL, '101868383', 'PROP, LIGHTWEIGHT, BIOPROP, 100 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('312', '3', NULL, '101868880', 'Prop-RC Ceramic Plus-16/20, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('313', '3', NULL, '386506', 'Sand-Common White-16/40, 1.5T bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('314', '3', NULL, '101375818', 'Sand-Rocky Mountain WF White');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('315', '3', NULL, '101377732', 'Prop-Premium-16/20, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('316', '3', NULL, '101378308', 'Sand-Common White-60/70, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('317', '3', NULL, '101889615', 'SAND, GGL G2-16/30, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('318', '3', NULL, '101889619', 'SAND, PREMIUM BROWN - 40/70, 3307 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('319', '3', NULL, '101385679', 'Sand-PRC-25/50, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('320', '3', NULL, '101902538', 'PROP, SINTERBALL LOCK 20/40, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('321', '3', NULL, '101388699', 'Prop-RC Ceramic Plus-12/18, 3200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('322', '3', NULL, '101909385', 'PROP,BAUXLITE PLUS CTD 16/20,3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('323', '3', NULL, '101909386', 'PROP, BAUXLITE PLUS 20/40, 3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('324', '3', NULL, '101909387', 'PROP,BAUXLITE PLUS CTD 20/40,3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('325', '3', NULL, '101910068', 'PROP, CARBOLITE CERAMIC PLUS-16/30, BLK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('326', '3', NULL, '101910069', 'PROP, CARBOLITE 20/40 COATED, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('327', '3', NULL, '101910070', 'PROP, CARBOLITE 16/30 COATED, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('328', '3', NULL, '101391217', 'PROP, VERSAPROP RC, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('329', '3', NULL, '101393255', 'Sand-Premium-30/70, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('330', '3', NULL, '101393318', 'Prop-Premium-70/140, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('331', '3', NULL, '101922445', 'PROP, FORES 20/40, 1000 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('332', '3', NULL, '101922446', 'PROP, ForeRCP 16/30, 1000 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('333', '3', NULL, '101403865', 'Sand-CRC Premium Plus-12/20, 4000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('334', '3', NULL, '101929099', 'SAND, PREMIUM BROWN 40/70, BULK BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('335', '3', NULL, '101933673', 'PROP, SINTER BLAST 40/120, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('336', '3', NULL, '101938572', 'PROP, BORPROP 16/30, 1000 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('337', '3', NULL, '101409645', 'Prop-Ceramax XRT-I-20/40, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('338', '3', NULL, '101409236', 'Prop-Premium Plus-12/18, 50 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('339', '3', NULL, '101410715', 'Sand-Premium White-30/70, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('340', '3', NULL, '101942038', 'SAND, EXTRALITE 12/20, SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('341', '3', NULL, '101942039', 'SAND, EXTRALITE 16/30, SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('342', '3', NULL, '101942040', 'SAND, EXTRALITE 20/40, SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('343', '3', NULL, '101942041', 'SAND, SUPER LITE 10/20, SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('344', '3', NULL, '101942047', 'SAND, SUPER LITE 16/30, SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('345', '3', NULL, '101942048', 'SAND, SUPER LITE 20/40, SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('346', '3', NULL, '101946650', 'SAND, BADGER PAC 20/40, MT');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('347', '3', NULL, '101419218', 'Sand-CRC Premium Plus-20/40,3200 Lb Bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('348', '3', NULL, '101951039', 'PROP, POWERPROP 30/50, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('349', '3', NULL, '101951135', 'SAND, SUPERLITE LOCK 10/20, 100 LB SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('350', '3', NULL, '101952458', 'SAND, EXTRALITE LOCK 12/20, 100 LB SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('351', '3', NULL, '101955407', 'SAND, EXTRALITE LOCK 16/30, 100 LB SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('352', '3', NULL, '101955498', 'EXTRA LITE LOCK 20/40 100 LB SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('353', '3', NULL, '101424677', 'Prop-Fores-RC Ceramic-10/14, 1000 kg bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('354', '3', NULL, '101426113', 'Prop-Premium Plus-14/20, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('355', '3', NULL, '101967327', 'PROP-VALUPROP V, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('356', '3', NULL, '101967371', 'SAND, SCHLINGMEYER S30T - 25 KG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('357', '3', NULL, '101207383', 'Sand-Premium White ReS 16/30,3000 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('358', '3', NULL, '101436319', 'Prop-Ceramax-XRT-E-20/40, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('359', '3', NULL, '101978570', 'CARBO NRT, LB');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('360', '3', NULL, '101438272', 'Prop-Versaprop, 50 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('361', '3', NULL, '101439881', 'Sand-Premium White-16/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('362', '3', NULL, '101443361', 'Prop-Ceramax XRT-P-16/30, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('363', '3', NULL, '101453048', 'Prop-HSP TA-20/40, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('364', '3', NULL, '101453050', 'Prop-HSP TC-20/40, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('365', '3', NULL, '101453049', 'Prop-HSP TB-20/40, Bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('366', '3', NULL, '120122385', 'Sand-Premium Brown-40/70, bulk');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('367', '3', NULL, '101458707', 'Sand-Premium White ReS-20/40,2200 lb bag');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('368', '3', NULL, '101469160', 'GRAVEL 16/40 LIGHT WEIGHT, 2400 LB');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('369', '3', NULL, '101209458', 'Sand-Premium White-20/40, 55 lb sack');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('370', '3', NULL, '70020', '30/50 ECONOPROP');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('371', '3', NULL, '102133307', 'PROP, BAUXLITE 16/30, 3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('372', '3', NULL, '102134042', 'PROP,BAUXLITE 20/40, 3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('373', '3', NULL, '102134158', 'PROP,BAUXLITE 30/50, 3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('374', '3', NULL, '102134161', 'PROP,BAUXLITE 40/80, 3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('375', '3', NULL, '102134221', 'PROP,BAUXLITE CTD 16/30, 3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('376', '3', NULL, '102134234', 'PROP,BAUXLITE CTD 20/40, 3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('377', '3', NULL, '102134249', 'PROP,BAUXLITE CTD 30/50, 3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('378', '3', NULL, '102134279', 'PROP,BAUXLITE CTD 40/80, 3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('379', '3', NULL, '102145979', 'PROP,CARBOPROP 16/20, 1500 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('380', '3', NULL, '102158205', 'PROP, MONOPROP, 1000 KG OCTABIN');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('381', '3', NULL, '102158287', 'PROP, CARBONRT 16/20, 1500 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('382', '3', NULL, '102111655', 'SAND-PREMIUM WHITE 40/70 - 25 KG BUCKET');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('383', '3', NULL, '102136629', 'PROP,BAUXLITE PLUS CTD16/30,3200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('384', '3', NULL, '102134579', 'SAND,ECONOPROP NRT 30/50,100 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('385', '3', NULL, '102134622', 'SAND,CARBOLITE NRT 20/40,100 LB SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('386', '3', NULL, '102134671', 'SAND,ECONOPROP NRT 20/40, 100 LB SACK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('387', '3', NULL, '102145144', 'SINTERLITE MESH 50/150-1500 KG BIG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('388', '3', NULL, '102146441', 'PROP, CARBOPROP 20/40, 1500 KG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('389', '3', NULL, '102154642', 'PROP, OILPLUS 20/40, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('390', '3', NULL, '102154663', 'PROP, OILPLUS 30/50, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('391', '3', NULL, '102154672', 'PROP, OILPLUS 40/70, BULK');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('392', '3', NULL, '102173385', 'PROP,CERAMIC PLUS-30/50,30/60,3200LB BG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('393', '3', NULL, '102179891', 'SAND, SILICA SAND, 2200 LB BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('394', '3', NULL, '102114904', 'SINTERLITE MESH 30/60-1500 KG BIG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('395', '3', NULL, '102115122', 'SINTERLITE MESH 50/120-1500 KG BIG BAG');
INSERT INTO `silicore_site`.`prod_products_customers` (`id`, `customer_id`, `product_id`, `product_no`, `description`) VALUES ('396', '3', NULL, '102115102', 'SINTERLITE MESH 40/80 - 1500 KG BIG BAG');



