
/*******************************************************************************************************************************************
 * File Name: sp_gb_plc_ProdProductsInsert.sql
 * Project: silicore
 * Description:
 * Notes:
 * =========================================================================================================================================
 * Change Log ([MM/DD/YYYY]|[Developer]|[Task Ticket] - [Description])
 * =========================================================================================================================================
 * 11/01/2017|whildebrandt|KACE:16787 - Insert data for prod_products_final
 *
 ******************************************************************************************************************************************/
# insert data for prod_products_final
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('1', '100MESH', '1', '100MESH', '100 Mesh', 'F', '40000.20', '1441317', 'Sand Fracing 100 Mesh', 'tons', '4F81BD', '0', '0', '2011-04-21', '2014-09-15');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('2', '40/70MESH', '1', '4070MESH', '40/70 Mesh', 'F', '40000.20', '1441316', 'Sand Fracing 40/70 Mesh', 'tons', 'D99694', '10', '0', '2011-08-10', '2014-09-15');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('3', '200MESH', '1', '200MESH', '200 Mesh', 'F', '40000.20', '1441310', 'Sand Fracing 200 Mesh', 'tons', '008000', '20', '0', '2012-03-13', '2014-09-15');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('4', 'BRICKSAND', '1', 'BRICKSAND', 'Brick Sand', 'A', '40000.20', NULL, NULL, 'tons', NULL, '30', '0', '2012-03-13', '2015-12-08');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('5', 'COMMONFILL', NULL, 'COMMONFILL', 'Common Fill', 'A', '40000.20', NULL, NULL, 'tons', NULL, '40', '0', '2014-10-14', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('6', 'CUSHIONSAND', '1', 'CUSHIONSAND', 'Cushion Sand', 'A', '40000.20', NULL, NULL, 'tons', NULL, '50', '0', '2011-06-30', '2014-09-15');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('7', 'SELECTFILL', NULL, 'SELECTFILL', 'Select Fill Dirt', 'A', '40000.20', NULL, NULL, 'tons', NULL, '60', '0', '2012-03-13', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('8', 'WASHEDSAND', '1', 'WASHEDSAND', 'Washed Sand ', 'A', '40000.20', NULL, NULL, 'tons', NULL, '70', '0', '2012-07-09', '2014-09-15');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('9', '2040MESH', '1', '2040MESH', '20/40 Mesh', 'F', '42122.20', '1441312', 'Sand Fracing 20/40 Mesh', 'tons', 'FFFF00', '25', '0', '2013-12-03', '2014-09-15');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('10', '30/50MESH', '1', '3050MESH', '30/50 Mesh', 'F', '42122.20', '1441313', 'Sand Fracing 30/50 Mesh', 'tons', 'B1A0C7', '27', '0', '2014-01-10', '2014-09-15');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('11', 'TRANSPORT', '1', 'TRANSPORT', 'Storage Transport', 'T', '50050.20', NULL, NULL, NULL, NULL, '999', '0', '2013-01-23', '2013-01-28');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('12', '16/30', '1', '1630', '16/30 Mesh', 'F', '40000.20', '1441311', 'Sand Fracing 16/30 Mesh', 'tons', NULL, '0', '0', '2014-05-21', '2014-09-15');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('13', '20/40MESHRESIN', '3', '2040MESHRESIN', '20/40 Mesh Resin', 'F', '40000.20', NULL, NULL, 'tons', NULL, '26', '0', '2015-10-22', '2015-10-22');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('14', 'TRUCKING', NULL, 'TRUCKING', 'Truck Haul', 'T', '50050.30', NULL, NULL, 'tons', NULL, '950', '0', '2011-11-08', '2014-09-04');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('15', 'TRANSLOAD', NULL, 'TRANSLOAD', 'Transload Fees', 'T', '50050.27', NULL, NULL, 'tons', NULL, '951', '0', '2014-09-04', '2015-11-19');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('16', 'RAILCAR', NULL, 'RAILCAR', 'Railcar Fees', 'T', '50050.50', NULL, NULL, 'tons', NULL, '952', '0', '2014-09-04', '2016-12-28');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('17', 'RAILTRANSPORT', NULL, 'RAILTRANSPORT', 'Rail Freight Fees', 'T', '50050.40', NULL, NULL, 'tons', NULL, '953', '0', '2014-09-04', '2015-05-21');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('18', 'FINCHG', NULL, 'FINCHG', 'Finance Charge', 'A', '10300.00', NULL, NULL, 'tons', NULL, '0', '0', NULL, NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('19', 'TEXT', NULL, 'TEXT', 'Text-only line item', 'A', '10000.00', NULL, NULL, 'tons', NULL, '0', '0', NULL, NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('20', 'UNAPPLIED', NULL, 'UNAPPLIED', 'Unapplied Payment', 'A', '10000.00', NULL, NULL, 'tons', NULL, '0', '0', NULL, NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('21', 'DEPOSIT', NULL, 'DEPOSIT', 'Deposit With Order', 'A', '10000.00', NULL, NULL, 'tons', NULL, '0', '0', NULL, NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('22', 'DM', NULL, 'DM', 'Direct Material', 'A', '10000.00', NULL, NULL, 'tons', NULL, '0', '0', NULL, NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('23', 'DL', NULL, 'DL', 'Direct Labor', 'A', '10000.00', NULL, NULL, 'tons', NULL, '0', '0', NULL, NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('24', 'SUB', NULL, 'SUB', 'Subcontractor', 'A', '10000.00', NULL, NULL, 'tons', NULL, '0', '0', NULL, NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('25', 'ODC', NULL, 'ODC', 'Other Direct Costs', 'A', '10000.00', NULL, NULL, 'tons', NULL, '0', '0', NULL, NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('26', 'OVH', NULL, 'OVH', 'Overhead', 'A', '10000.00', NULL, NULL, 'tons', NULL, '0', '0', NULL, NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('27', 'OTH', NULL, 'OTH', 'Other', 'A', '10000.00', NULL, NULL, 'tons', NULL, '0', '0', NULL, NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('28', 'OFFICEEXP', NULL, 'OFFICEEXP', 'Office / General Expenses', 'A', '56999.20', NULL, NULL, 'tons', NULL, '0', '0', '2011-08-05', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('29', 'TRUCKING:DEMURRAGE', NULL, 'TRUCKINGDEMURRAGE', 'Demurrage Hours', 'A', '54029.27', NULL, NULL, 'tons', NULL, '0', '0', '2011-11-08', '2016-03-08');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('30', 'ROCK', NULL, 'ROCK', 'Rock', 'A', '42007.20', NULL, NULL, 'tons', NULL, '0', '0', '2012-03-26', '2013-01-07');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('31', 'STORAGE', NULL, 'STORAGE', 'Sand Storage ', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2012-05-10', '2013-01-07');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('32', 'WATER', NULL, 'WATER', 'Water', 'A', '60000.00', NULL, NULL, 'tons', NULL, '0', '0', '2012-12-28', '2013-01-07');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('33', 'TRANSLOADERS', NULL, 'TRANSLOADERS', 'Railyard', 'A', '70000.90', NULL, NULL, 'tons', NULL, '0', '0', '2013-05-17', '2013-05-30');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('34', 'EMPLOYEES', NULL, 'EMPLOYEES', 'Railyard Employees', 'A', '70005.90', NULL, NULL, 'tons', NULL, '0', '0', '2013-05-17', '2013-05-30');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('35', 'SAFETYTRAINING', NULL, 'SAFETYTRAINING', 'Safety training and set up for new employees', 'A', '70015.90', NULL, NULL, 'tons', NULL, '0', '0', '2013-05-17', '2013-05-30');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('36', 'OVERTIME', NULL, 'OVERTIME', 'Employee overtime for the railyard', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2013-05-17', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('37', 'IN*GRESS', NULL, 'INGRESS', 'Entry to the railyard', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2013-05-17', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('38', 'EGRESS', NULL, 'EGRESS', 'Exiting the railyard', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2013-05-17', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('39', 'DUSTCONTROL', NULL, 'DUSTCONTROL', 'Dust Control', 'A', '70010.90', NULL, NULL, 'tons', NULL, '0', '0', '2013-05-30', '2013-05-30');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('40', 'SAFETY-TRACWORKS', NULL, 'SAFETYTRACWORKS', 'Safety', 'A', '70015.90', NULL, NULL, 'tons', NULL, '0', '0', '2013-06-04', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('41', 'RAILCARS', NULL, 'RAILCARS', 'Rebate', 'A', '45100.20', NULL, NULL, 'tons', NULL, '0', '0', '2013-06-13', '2014-12-11');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('42', 'SILOFIXEDBILLING', NULL, 'SILOFIXEDBILLING', 'Silo Fixed Billing', 'A', '60001.00', NULL, NULL, 'tons', NULL, '0', '0', '2013-08-26', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('43', 'BENTONITE', '1', 'BENTONITE', 'Halliburton Bentonite', 'A', '50050.27', NULL, NULL, 'tons', NULL, '0', '0', '2014-01-06', '2014-09-15');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('44', '30/70MESH', '1', '3070MESH', '30/70 Mesh', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2014-07-18', '2014-09-15');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('45', 'LEASEDCARS', NULL, 'LEASEDCARS', 'Leased rail cars', 'A', '50050.50', NULL, NULL, 'tons', NULL, '0', '0', '2014-07-30', '2014-10-13');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('46', 'UFWASHEDSAND', NULL, 'UFWASHEDSAND', 'UF Washedsand', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2015-01-08', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('47', 'OILPLUS-30/50', NULL, 'OILPLUS3050', 'Hexion OilPlus 30/50 Transload', 'A', '50050.27', NULL, NULL, 'tons', NULL, '0', '0', '2015-07-09', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('48', 'OILPLUS-40/70', NULL, 'OILPLUS4070', 'Hexion OilPlus 40/70 Transload', 'A', '50050.27', NULL, NULL, 'tons', NULL, '0', '0', '2015-07-09', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('49', 'LINEADJ', '5', 'LINEADJ', 'PRICE ADJUSTMENT', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2015-10-08', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('50', 'TRANSLOAD-DILLEY', NULL, 'TRANSLOADDILLEY', 'TRANSLOAD-DILLEY', 'A', '50050.80', NULL, NULL, 'tons', NULL, '0', '0', '2015-11-25', '2015-11-25');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('51', 'OTHER', '5', 'OTHER', 'OTHER', 'A', '99999.20', NULL, NULL, 'tons', NULL, '0', '0', '2015-12-21', '2016-06-30');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('52', 'OTHER-20/40', NULL, 'OTHER 20/40', 'SiberProp 20/40', 'A', '50050.27', NULL, NULL, 'tons', NULL, '0', '0', '2016-02-22', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('53', '30/50SLC', NULL, '3050SLC', '30/50SLC', 'A', '49999.20', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-02', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('54', '30/50SDC', NULL, '3050SDC', '30/50SDC', 'A', '49999.20', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-02', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('55', '20/40THS', NULL, '2040THS', '20/40 THS', 'A', '50050.21', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-04', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('56', '16/30BLKULT', NULL, '1630BLKULT', '16/30 Black Ultra', 'A', '50050.21', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-10', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('57', '16/30SIBPRP', NULL, '1630SIBPRP', '16/30 Siber Prop', 'A', '50050.21', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-10', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('58', '20/4BERISP', NULL, '204BERISP', '20/40 Berry ISP', 'A', '50050.21', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-10', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('59', '20/4COLSET', NULL, '204COLSET', '20/40 Cool Set', 'A', '50050.21', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-10', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('60', '20/4ECNPRP', NULL, '204ECNPRP', '20/40 Econoprop', 'A', '50050.21', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-10', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('61', '20/40GARNET', NULL, '2040GARNET', '20/40 Garnet', 'A', '50050.21', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-10', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('62', '20/4OPTPRP', NULL, '204OPTPRP', '20/40 Opti Prop', 'A', '50050.21', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-10', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('63', '30/50ATL', NULL, '3050ATL', '30/50 ATLAS', 'A', '50050.21', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-10', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('64', '30/50ATLCRC', NULL, '3050ATLCRC', '30/50 Atlas CRC-C', 'A', '50050.21', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-10', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('65', '30/50BLKULT', NULL, '3050BLKULT', '30/50 Black Ultra', 'A', '50050.21', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-10', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('66', '30/5BRADY', NULL, '305BRADY', '30/50 Brady', 'A', '50050.21', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-10', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('67', '30/50CRBBND', NULL, '3050CRBBND', '30/50 Carbo Bond', 'A', '50050.21', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-10', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('68', 'CONTAMINATED', NULL, 'CONTAMINATED', 'Contaminated', 'A', '50050.21', NULL, NULL, 'tons', NULL, '0', '0', '2016-05-10', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('69', '3050PRIMEPLUS', NULL, '3050PRIMEPLUS', '30/50 Prime Plus', 'A', '50050.21', NULL, NULL, 'tons', NULL, '0', '0', '2016-06-28', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('70', 'DL100M', NULL, 'DL100M', 'DUSTLESS 100 MESH', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2016-07-11', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('71', 'DL40/70M', NULL, 'DL4070M', 'DUSTLESS 40/70 MESH', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2016-07-11', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('72', 'FRT-OS', '4', 'FRTOS', 'Interstate Freight', 'A', '50050.40', NULL, NULL, 'tons', NULL, '0', '0', '2016-07-26', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('73', 'HOBBS100', '1', 'HOBBS100', '100 MESH', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2016-07-26', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('74', 'HOBBS4070', NULL, 'HOBBS4070', '40/70 MESH', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2016-07-26', NULL);
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('75', '70/240MESH', '1', '70240MESH', '70/240Mesh', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2016-11-22', '2016-11-22');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('76', 'STOCK', NULL, 'STOCK', '_', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2016-12-30', '2016-12-30');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('77', 'NONSTOCK', NULL, 'NONSTOCK', '_', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2016-12-30', '2016-12-30');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('78', 'SERVICES', NULL, 'SERVICES', '_', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2016-12-30', '2016-12-30');
INSERT INTO `silicore_site`.`prod_products_final` (`id`, `cyma_product_id`, `cyma_product_line_id`, `transcore_product_no`, `description`, `type_code`, `cyma_account`, `stcc`, `stcc_description`, `units`, `color_code_hex`, `sort_order`, `is_removed`, `cyma_create_date`, `cyma_edit_date`) VALUES ('79', 'RENTAL', NULL, 'RENTAL', '_', 'A', '40000.20', NULL, NULL, 'tons', NULL, '0', '0', '2016-12-30', '2016-12-30');



