/*******************************************************************************************************************************************
 * File Name: qc_locations_details.sql
 * Project: Sandbox
 * Author: kkuehn, mnutsch
 * Date Created: 6-15-2017
 * Description: 
 * Notes: 
 ******************************************************************************************************************************************/

DROP TABLE IF EXISTS `gb_qc_locations_details`;

CREATE TABLE `gb_qc_locations_details` (
  `id` int(11) NOT NULL,
  `qc_location_id` int(11) NOT NULL,
  `description` varchar(256) NOT NULL,
  `sort_order` int(11) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

# INSERT LEGACY BACKOFFICE DATA HERE
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('0', '0', 'NA', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('1', '3', 'Wet Plant Gate 01', '1', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('2', '3', 'Wet Plant Gate 02', '2', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('3', '3', 'Wet Plant Gate 03', '3', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('4', '3', 'Wet Plant Gate 04', '4', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('5', '3', 'Wet Plant Gate 05', '5', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('6', '3', 'Wet Plant Gate 06', '6', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('7', '3', 'Wet Plant Gate 07', '7', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('8', '3', 'Wet Plant Gate 08', '8', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('9', '3', 'Wet Plant Gate 09', '9', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('10', '3', 'Wet Plant Gate 10', '10', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('11', '3', 'Wet Plant Gate 11', '11', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('12', '3', 'Wet Plant Gate 12', '12', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('13', '3', 'Wet Plant Gate 13', '13', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('14', '3', 'Wet Plant Gate 14', '14', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('15', '3', 'Wet Plant Gate 15', '15', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('16', '3', 'Wet Plant Gate 16', '16', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('17', '3', 'Wet Plant Gate 17', '17', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('18', '3', 'Wet Plant Gate 18', '18', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('19', '4', 'Wet Plant Gate 01', '19', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('20', '4', 'Wet Plant Gate 02', '20', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('21', '4', 'Wet Plant Gate 03', '21', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('22', '4', 'Wet Plant Gate 04', '22', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('23', '4', 'Wet Plant Gate 05', '23', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('24', '4', 'Wet Plant Gate 06', '24', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('25', '4', 'Wet Plant Gate 07', '25', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('26', '4', 'Wet Plant Gate 08', '26', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('27', '4', 'Wet Plant Gate 09', '27', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('28', '4', 'Wet Plant Gate 10', '28', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('29', '4', 'Wet Plant Gate 11', '29', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('30', '4', 'Wet Plant Gate 12', '30', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('31', '4', 'Wet Plant Gate 13', '31', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('32', '4', 'Wet Plant Gate 14', '32', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('33', '4', 'Wet Plant Gate 15', '33', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('34', '4', 'Wet Plant Gate 16', '34', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('35', '4', 'Wet Plant Gate 17', '35', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('36', '4', 'Wet Plant Gate 18', '36', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('37', '9', 'Wet Plant Gate 01', '37', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('38', '9', 'Wet Plant Gate 02', '38', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('39', '9', 'Wet Plant Gate 03', '39', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('40', '9', 'Wet Plant Gate 04', '40', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('41', '9', 'Wet Plant Gate 05', '41', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('42', '9', 'Wet Plant Gate 06', '42', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('43', '9', 'Wet Plant Gate 07', '43', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('44', '9', 'Wet Plant Gate 08', '44', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('45', '9', 'Wet Plant Gate 09', '45', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('46', '9', 'Wet Plant Gate 10', '46', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('47', '9', 'Wet Plant Gate 11', '47', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('48', '9', 'Wet Plant Gate 12', '48', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('49', '9', 'Wet Plant Gate 13', '49', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('50', '9', 'Wet Plant Gate 14', '50', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('51', '9', 'Wet Plant Gate 15', '51', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('52', '9', 'Wet Plant Gate 16', '52', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('53', '9', 'Wet Plant Gate 17', '53', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('54', '9', 'Wet Plant Gate 18', '54', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('55', '3', 'Stockpile 01 (Wet Plant Coarse 1)', '61', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('56', '9', 'Stockpile 01 (Wet Plant Coarse 1)', '62', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('57', '4', 'Stockpile 02 (Wet Plant Fine 1)', '63', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('58', '4', 'Stockpile 03 (Wet Plant Fine 2)', '64', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('59', '9', 'Stockpile 02 (Wet Plant Fine 1)', '66', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('60', '9', 'Stockpile 03 (Wet Plant Fine 2)', '67', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('61', '20', 'Stockpile 04 (Old Wet Plant Coarse 1)', '68', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('62', '20', 'Stockpile 05 (Old Wet Plant Coarse 2)', '69', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('63', '20', 'Stockpile 06 (Old Wet Plant Coarse 3)', '70', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('64', '20', 'Stockpile 07 (Old Wet Plant Coarse 4)', '71', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('65', '20', 'Stockpile 08 (Old Wet Plant Coarse 5)', '72', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('66', '22', 'Stockpile 04 (Old Wet Plant Coarse 1)', '73', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('67', '22', 'Stockpile 05 (Old Wet Plant Coarse 2)', '74', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('68', '22', 'Stockpile 06 (Old Wet Plant Coarse 3)', '75', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('69', '22', 'Stockpile 07 (Old Wet Plant Coarse 4)', '76', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('70', '22', 'Stockpile 08 (Old Wet Plant Coarse 5)', '77', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('71', '9', 'Stockpile 04 (Old Wet Plant Coarse 1)', '78', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('72', '9', 'Stockpile 05 (Old Wet Plant Coarse 2)', '79', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('73', '9', 'Stockpile 06 (Old Wet Plant Coarse 3)', '80', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('74', '9', 'Stockpile 07 (Old Wet Plant Coarse 4)', '81', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('75', '9', 'Stockpile 08 (Old Wet Plant Coarse 5)', '82', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('76', '21', 'Stockpile 09 (Old Wet Plant Fine 1)', '83', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('77', '21', 'Stockpile 10 (Old Wet Plant Fine 2)', '84', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('78', '21', 'Stockpile 11 (Old Wet Plant Fine 3)', '85', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('79', '21', 'Stockpile 12 (Old Wet Plant Fine 4)', '86', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('80', '21', 'Stockpile 13 (Old Wet Plant Fine 5)', '87', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('81', '23', 'Stockpile 09 (Old Wet Plant Fine 1)', '88', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('82', '23', 'Stockpile 10 (Old Wet Plant Fine 2)', '89', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('83', '23', 'Stockpile 11 (Old Wet Plant Fine 3)', '90', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('84', '23', 'Stockpile 12 (Old Wet Plant Fine 4)', '91', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('85', '23', 'Stockpile 13 (Old Wet Plant Fine 5)', '92', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('86', '9', 'Stockpile 09 (Old Wet Plant Fine 1)', '93', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('87', '9', 'Stockpile 10 (Old Wet Plant Fine 2)', '94', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('88', '9', 'Stockpile 11 (Old Wet Plant Fine 3)', '95', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('89', '9', 'Stockpile 12 (Old Wet Plant Fine 4)', '96', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('90', '9', 'Stockpile 13 (Old Wet Plant Fine 5)', '97', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('91', '14', 'Stockpile 14 (Dry Plant Coarse 1)', '98', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('92', '16', 'Stockpile 14 (Dry Plant Coarse 1)', '99', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('93', '9', 'Stockpile 14 (Dry Plant Coarse 1)', '100', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('94', '13', 'Stockpile 15 (Dry Plant Fine 1)', '101', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('95', '15', 'Stockpile 15 (Dry Plant Fine 1)', '102', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('96', '17', 'Stockpile 15 (Dry Plant Fine 1)', '103', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('97', '9', 'Stockpile 15 (Dry Plant Fine 1)', '104', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('98', '11', 'Wet Plant Gate 01', '105', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('99', '11', 'Wet Plant Gate 02', '106', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('100', '11', 'Wet Plant Gate 03', '107', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('101', '11', 'Wet Plant Gate 04', '108', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('102', '11', 'Wet Plant Gate 05', '109', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('103', '11', 'Wet Plant Gate 06', '110', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('104', '11', 'Wet Plant Gate 07', '111', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('105', '11', 'Wet Plant Gate 08', '112', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('106', '11', 'Wet Plant Gate 09', '113', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('107', '11', 'Wet Plant Gate 10', '114', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('108', '11', 'Wet Plant Gate 11', '115', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('109', '11', 'Wet Plant Gate 12', '116', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('110', '11', 'Wet Plant Gate 13', '117', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('111', '11', 'Wet Plant Gate 14', '118', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('112', '11', 'Wet Plant Gate 15', '119', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('113', '11', 'Wet Plant Gate 16', '120', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('114', '11', 'Stockpile 01 (Wet Plant Coarse 1)', '121', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('115', '11', 'Stockpile 02 (Wet Plant Fine 1)', '122', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('116', '11', 'Stockpile 03 (Wet Plant Fine 2)', '123', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('117', '11', 'Stockpile 04 (Old Wet Plant Coarse 1)', '124', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('118', '11', 'Stockpile 05 (Old Wet Plant Coarse 2)', '125', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('119', '11', 'Stockpile 06 (Old Wet Plant Coarse 3)', '126', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('120', '11', 'Stockpile 07 (Old Wet Plant Coarse 4)', '127', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('121', '11', 'Stockpile 08 (Old Wet Plant Coarse 5)', '128', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('122', '11', 'Stockpile 09 (Old Wet Plant Fine 1)', '129', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('123', '11', 'Stockpile 10 (Old Wet Plant Fine 2)', '130', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('124', '11', 'Stockpile 11 (Old Wet Plant Fine 3)', '131', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('125', '11', 'Stockpile 12 (Old Wet Plant Fine 4)', '132', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('126', '11', 'Stockpile 13 (Old Wet Plant Fine 5)', '133', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('127', '11', 'Stockpile 14 (Dry Plant Coarse 1)', '134', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('128', '11', 'Stockpile 15 (Dry Plant Fine 1)', '135', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('129', '12', 'Wet Plant Gate 09', '136', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('130', '12', 'Wet Plant Gate 10', '137', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('131', '12', 'Wet Plant Gate 11', '138', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('132', '12', 'Wet Plant Gate 12', '139', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('133', '12', 'Wet Plant Gate 13', '140', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('134', '12', 'Wet Plant Gate 14', '141', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('135', '12', 'Wet Plant Gate 15', '142', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('136', '12', 'Wet Plant Gate 16', '143', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('137', '12', 'Stockpile 02 (Wet Plant Fine 1)', '144', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('138', '12', 'Stockpile 03 (Wet Plant Fine 2)', '145', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('139', '12', 'Stockpile 09 (Old Wet Plant Fine 1)', '146', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('140', '12', 'Stockpile 10 (Old Wet Plant Fine 2)', '147', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('141', '12', 'Stockpile 11 (Old Wet Plant Fine 3)', '148', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('142', '12', 'Stockpile 12 (Old Wet Plant Fine 4)', '149', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('143', '12', 'Stockpile 13 (Old Wet Plant Fine 5)', '150', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('144', '12', 'Stockpile 15 (Dry Plant Fine 1)', '151', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('145', '13', 'Wet Plant Gate 01', '152', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('146', '13', 'Wet Plant Gate 02', '153', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('147', '13', 'Wet Plant Gate 03', '154', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('148', '13', 'Wet Plant Gate 04', '155', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('149', '13', 'Wet Plant Gate 05', '156', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('150', '13', 'Wet Plant Gate 06', '157', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('151', '13', 'Wet Plant Gate 07', '158', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('152', '13', 'Wet Plant Gate 08', '159', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('153', '13', 'Wet Plant Gate 09', '160', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('154', '13', 'Wet Plant Gate 10', '161', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('155', '13', 'Wet Plant Gate 11', '162', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('156', '13', 'Wet Plant Gate 12', '163', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('157', '13', 'Wet Plant Gate 13', '164', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('158', '13', 'Wet Plant Gate 14', '165', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('159', '13', 'Wet Plant Gate 15', '166', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('160', '13', 'Wet Plant Gate 16', '167', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('161', '13', 'Stockpile 01 (Wet Plant Coarse 1)', '168', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('162', '13', 'Stockpile 02 (Wet Plant Fine 1)', '169', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('163', '13', 'Stockpile 03 (Wet Plant Fine 2)', '170', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('164', '13', 'Stockpile 04 (Old Wet Plant Coarse 1)', '171', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('165', '13', 'Stockpile 05 (Old Wet Plant Coarse 2)', '172', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('166', '13', 'Stockpile 06 (Old Wet Plant Coarse 3)', '173', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('167', '13', 'Stockpile 07 (Old Wet Plant Coarse 4)', '174', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('168', '13', 'Stockpile 08 (Old Wet Plant Coarse 5)', '175', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('169', '13', 'Stockpile 09 (Old Wet Plant Fine 1)', '176', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('170', '13', 'Stockpile 10 (Old Wet Plant Fine 2)', '177', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('171', '13', 'Stockpile 11 (Old Wet Plant Fine 3)', '178', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('172', '13', 'Stockpile 12 (Old Wet Plant Fine 4)', '179', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('173', '13', 'Stockpile 13 (Old Wet Plant Fine 5)', '180', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('174', '13', 'Stockpile 14 (Dry Plant Coarse 1)', '181', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('175', '13', 'Stockpile 15 (Dry Plant Fine 1)', '182', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('176', '14', 'Wet Plant Gate 01', '183', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('177', '14', 'Wet Plant Gate 02', '184', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('178', '14', 'Wet Plant Gate 03', '185', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('179', '14', 'Wet Plant Gate 04', '186', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('180', '14', 'Wet Plant Gate 05', '187', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('181', '14', 'Wet Plant Gate 06', '188', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('182', '14', 'Wet Plant Gate 07', '189', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('183', '14', 'Wet Plant Gate 08', '190', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('184', '14', 'Stockpile 01 (Wet Plant Coarse 1)', '191', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('185', '14', 'Stockpile 04 (Old Wet Plant Coarse 1)', '192', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('186', '14', 'Stockpile 05 (Old Wet Plant Coarse 2)', '193', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('187', '14', 'Stockpile 06 (Old Wet Plant Coarse 3)', '194', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('188', '14', 'Stockpile 07 (Old Wet Plant Coarse 4)', '195', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('189', '14', 'Stockpile 08 (Old Wet Plant Coarse 5)', '196', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('190', '14', 'Stockpile 14 (Dry Plant Coarse 1)', '197', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('191', '16', 'Wet Plant Gate 01', '198', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('192', '16', 'Wet Plant Gate 02', '199', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('193', '16', 'Wet Plant Gate 03', '200', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('194', '16', 'Wet Plant Gate 04', '201', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('195', '16', 'Wet Plant Gate 05', '202', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('196', '16', 'Wet Plant Gate 06', '203', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('197', '16', 'Wet Plant Gate 07', '204', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('198', '16', 'Wet Plant Gate 08', '205', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('199', '16', 'Stockpile 01 (Wet Plant Coarse 1)', '206', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('200', '16', 'Stockpile 04 (Old Wet Plant Coarse 1)', '207', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('201', '16', 'Stockpile 05 (Old Wet Plant Coarse 2)', '208', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('202', '16', 'Stockpile 06 (Old Wet Plant Coarse 3)', '209', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('203', '16', 'Stockpile 07 (Old Wet Plant Coarse 4)', '210', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('204', '16', 'Stockpile 08 (Old Wet Plant Coarse 5)', '211', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('205', '16', 'Stockpile 14 (Dry Plant Coarse 1)', '212', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('206', '15', 'Wet Plant Gate 09', '221', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('207', '15', 'Wet Plant Gate 10', '222', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('208', '15', 'Wet Plant Gate 11', '223', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('209', '15', 'Wet Plant Gate 12', '224', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('210', '15', 'Wet Plant Gate 13', '225', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('211', '15', 'Wet Plant Gate 14', '226', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('212', '15', 'Wet Plant Gate 15', '227', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('213', '15', 'Wet Plant Gate 16', '228', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('214', '15', 'Stockpile 02 (Wet Plant Fine 1)', '230', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('215', '15', 'Stockpile 03 (Wet Plant Fine 2)', '231', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('216', '15', 'Stockpile 09 (Old Wet Plant Fine 1)', '237', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('217', '15', 'Stockpile 10 (Old Wet Plant Fine 2)', '238', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('218', '15', 'Stockpile 11 (Old Wet Plant Fine 3)', '239', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('219', '15', 'Stockpile 12 (Old Wet Plant Fine 4)', '240', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('220', '15', 'Stockpile 13 (Old Wet Plant Fine 5)', '241', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('221', '15', 'Stockpile 15 (Dry Plant Fine 1)', '243', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('222', '17', 'Wet Plant Gate 09', '252', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('223', '17', 'Wet Plant Gate 10', '253', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('224', '17', 'Wet Plant Gate 11', '254', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('225', '17', 'Wet Plant Gate 12', '255', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('226', '17', 'Wet Plant Gate 13', '256', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('227', '17', 'Wet Plant Gate 14', '257', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('228', '17', 'Wet Plant Gate 15', '258', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('229', '17', 'Wet Plant Gate 16', '259', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('230', '17', 'Stockpile 02 (Wet Plant Fine 1)', '261', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('231', '17', 'Stockpile 03 (Wet Plant Fine 2)', '262', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('232', '17', 'Stockpile 09 (Old Wet Plant Fine 1)', '268', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('233', '17', 'Stockpile 10 (Old Wet Plant Fine 2)', '269', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('234', '17', 'Stockpile 11 (Old Wet Plant Fine 3)', '270', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('235', '17', 'Stockpile 12 (Old Wet Plant Fine 4)', '271', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('236', '17', 'Stockpile 13 (Old Wet Plant Fine 5)', '272', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('237', '17', 'Stockpile 15 (Dry Plant Fine 1)', '274', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('238', '15', 'Wet Plant Gate 01', '213', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('239', '15', 'Wet Plant Gate 02', '214', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('240', '15', 'Wet Plant Gate 03', '215', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('241', '15', 'Wet Plant Gate 04', '216', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('242', '15', 'Wet Plant Gate 05', '217', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('243', '15', 'Wet Plant Gate 06', '218', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('244', '15', 'Wet Plant Gate 07', '219', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('245', '15', 'Wet Plant Gate 08', '220', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('246', '15', 'Stockpile 01 (Wet Plant Coarse 1)', '229', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('247', '15', 'Stockpile 04 (Old Wet Plant Coarse 1)', '232', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('248', '15', 'Stockpile 05 (Old Wet Plant Coarse 2)', '233', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('249', '15', 'Stockpile 06 (Old Wet Plant Coarse 3)', '234', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('250', '15', 'Stockpile 07 (Old Wet Plant Coarse 4)', '235', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('251', '15', 'Stockpile 08 (Old Wet Plant Coarse 5)', '236', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('252', '15', 'Stockpile 14 (Dry Plant Coarse 1)', '242', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('253', '17', 'Wet Plant Gate 01', '244', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('254', '17', 'Wet Plant Gate 02', '245', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('255', '17', 'Wet Plant Gate 03', '246', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('256', '17', 'Wet Plant Gate 04', '247', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('257', '17', 'Wet Plant Gate 05', '248', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('258', '17', 'Wet Plant Gate 06', '249', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('259', '17', 'Wet Plant Gate 07', '250', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('260', '17', 'Wet Plant Gate 08', '251', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('261', '17', 'Stockpile 01 (Wet Plant Coarse 1)', '260', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('262', '17', 'Stockpile 04 (Old Wet Plant Coarse 1)', '263', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('263', '17', 'Stockpile 05 (Old Wet Plant Coarse 2)', '264', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('264', '17', 'Stockpile 06 (Old Wet Plant Coarse 3)', '265', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('265', '17', 'Stockpile 07 (Old Wet Plant Coarse 4)', '266', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('266', '17', 'Stockpile 08 (Old Wet Plant Coarse 5)', '267', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('267', '17', 'Stockpile 14 (Dry Plant Coarse 1)', '273', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('268', '24', 'Wet Plant Gate 09', '275', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('269', '24', 'Wet Plant Gate 10', '276', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('270', '24', 'Wet Plant Gate 11', '277', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('271', '24', 'Wet Plant Gate 12', '278', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('272', '24', 'Wet Plant Gate 13', '279', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('273', '24', 'Wet Plant Gate 14', '280', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('274', '24', 'Wet Plant Gate 15', '281', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('275', '24', 'Wet Plant Gate 16', '282', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('276', '24', 'Stockpile 02 (Wet Plant Fine 1)', '283', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('277', '24', 'Stockpile 03 (Wet Plant Fine 2)', '284', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('278', '24', 'Stockpile 09 (Old Wet Plant Fine 1)', '285', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('279', '24', 'Stockpile 10 (Old Wet Plant Fine 2)', '286', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('280', '24', 'Stockpile 11 (Old Wet Plant Fine 3)', '287', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('281', '24', 'Stockpile 12 (Old Wet Plant Fine 4)', '288', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('282', '24', 'Stockpile 13 (Old Wet Plant Fine 5)', '289', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('283', '24', 'Stockpile 15 (Dry Plant Fine 1)', '290', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('284', '20', 'Old Wet Plant Coarse Side A', '55', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('285', '20', 'Old Wet Plant Coarse Side B', '56', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('286', '20', 'Old Wet Plant Coarse Pile', '57', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('287', '21', 'Old Wet Plant Fine Side A', '58', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('288', '21', 'Old Wet Plant Fine Side B', '59', '0');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('289', '21', 'Old Wet Plant Fine Pile', '60', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('290', '4', 'Stockpile 16 (Wet Plant Fine 3)', '65', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('291', '22', 'Old Wet Plant Coarse Pile', '57', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('292', '23', 'Old Wet Plant Fine Pile', '60', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('293', '49', 'Wet Plant Gate 09', '136', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('294', '49', 'Wet Plant Gate 10', '137', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('295', '49', 'Wet Plant Gate 11', '138', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('296', '49', 'Wet Plant Gate 12', '139', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('297', '49', 'Wet Plant Gate 13', '140', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('298', '49', 'Wet Plant Gate 14', '141', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('299', '49', 'Wet Plant Gate 15', '142', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('300', '49', 'Wet Plant Gate 16', '143', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('301', '49', 'Stockpile 02 (Wet Plant Fine 1)', '144', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('302', '49', 'Stockpile 03 (Wet Plant Fine 2)', '145', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('303', '49', 'Stockpile 09 (Old Wet Plant Fine 1)', '146', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('304', '49', 'Stockpile 10 (Old Wet Plant Fine 2)', '147', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('305', '49', 'Stockpile 11 (Old Wet Plant Fine 3)', '148', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('306', '49', 'Stockpile 12 (Old Wet Plant Fine 4)', '149', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('307', '49', 'Stockpile 13 (Old Wet Plant Fine 5)', '150', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('308', '49', 'Stockpile 15 (Dry Plant Fine 1)', '151', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('309', '50', 'Wet Plant Gate 09', '160', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('310', '50', 'Wet Plant Gate 10', '161', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('311', '50', 'Wet Plant Gate 11', '162', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('312', '50', 'Wet Plant Gate 12', '163', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('313', '50', 'Wet Plant Gate 13', '164', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('314', '50', 'Wet Plant Gate 14', '165', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('315', '50', 'Wet Plant Gate 15', '166', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('316', '50', 'Wet Plant Gate 16', '167', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('317', '50', 'Stockpile 02 (Wet Plant Fine 1)', '169', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('318', '50', 'Stockpile 03 (Wet Plant Fine 2)', '170', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('319', '50', 'Stockpile 09 (Old Wet Plant Fine 1)', '176', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('320', '50', 'Stockpile 10 (Old Wet Plant Fine 2)', '177', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('321', '50', 'Stockpile 11 (Old Wet Plant Fine 3)', '178', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('322', '50', 'Stockpile 12 (Old Wet Plant Fine 4)', '179', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('323', '50', 'Stockpile 13 (Old Wet Plant Fine 5)', '180', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('324', '50', 'Stockpile 15 (Dry Plant Fine 1)', '182', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('325', '51', 'Wet Plant Gate 09', '183', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('326', '51', 'Wet Plant Gate 10', '184', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('327', '51', 'Wet Plant Gate 11', '185', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('328', '51', 'Wet Plant Gate 12', '186', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('329', '51', 'Wet Plant Gate 13', '187', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('330', '51', 'Wet Plant Gate 14', '188', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('331', '51', 'Wet Plant Gate 15', '189', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('332', '51', 'Wet Plant Gate 16', '190', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('333', '51', 'Stockpile 02 (Wet Plant Fine 1)', '191', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('334', '51', 'Stockpile 03 (Wet Plant Fine 2)', '192', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('335', '51', 'Stockpile 09 (Old Wet Plant Fine 1)', '193', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('336', '51', 'Stockpile 10 (Old Wet Plant Fine 2)', '194', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('337', '51', 'Stockpile 11 (Old Wet Plant Fine 3)', '195', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('338', '51', 'Stockpile 12 (Old Wet Plant Fine 4)', '196', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('339', '51', 'Stockpile 13 (Old Wet Plant Fine 5)', '197', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('340', '51', 'Stockpile 15 (Dry Plant Fine 1)', '198', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('341', '54', 'Wet Plant Gate 01', '199', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('342', '54', 'Wet Plant Gate 02', '200', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('343', '54', 'Wet Plant Gate 03', '201', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('344', '54', 'Wet Plant Gate 04', '202', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('345', '54', 'Wet Plant Gate 05', '203', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('346', '54', 'Wet Plant Gate 06', '204', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('347', '54', 'Wet Plant Gate 07', '205', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('348', '54', 'Wet Plant Gate 08', '206', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('349', '54', 'Stockpile 01 (Wet Plant Coarse 1)', '207', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('350', '54', 'Stockpile 04 (Old Wet Plant Coarse 1)', '208', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('351', '54', 'Stockpile 05 (Old Wet Plant Coarse 2)', '209', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('352', '54', 'Stockpile 06 (Old Wet Plant Coarse 3)', '210', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('353', '54', 'Stockpile 07 (Old Wet Plant Coarse 4)', '211', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('354', '54', 'Stockpile 08 (Old Wet Plant Coarse 5)', '212', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('355', '54', 'Stockpile 14 (Dry Plant Coarse 1)', '213', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('356', '55', 'Wet Plant Gate 01', '214', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('357', '55', 'Wet Plant Gate 02', '215', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('358', '55', 'Wet Plant Gate 03', '216', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('359', '55', 'Wet Plant Gate 04', '217', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('360', '55', 'Wet Plant Gate 05', '218', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('361', '55', 'Wet Plant Gate 06', '219', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('362', '55', 'Wet Plant Gate 07', '220', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('363', '55', 'Wet Plant Gate 08', '221', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('364', '55', 'Wet Plant Gate 09', '222', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('365', '55', 'Wet Plant Gate 10', '223', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('366', '55', 'Wet Plant Gate 11', '224', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('367', '55', 'Wet Plant Gate 12', '225', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('368', '55', 'Wet Plant Gate 13', '226', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('369', '55', 'Wet Plant Gate 14', '227', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('370', '55', 'Wet Plant Gate 15', '228', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('371', '55', 'Wet Plant Gate 16', '229', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('372', '55', 'Stockpile 01 (Wet Plant Coarse 1)', '230', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('373', '55', 'Stockpile 02 (Wet Plant Fine 1)', '231', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('374', '55', 'Stockpile 03 (Wet Plant Fine 2)', '232', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('375', '55', 'Stockpile 04 (Old Wet Plant Coarse 1)', '233', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('376', '55', 'Stockpile 05 (Old Wet Plant Coarse 2)', '234', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('377', '55', 'Stockpile 06 (Old Wet Plant Coarse 3)', '235', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('378', '55', 'Stockpile 07 (Old Wet Plant Coarse 4)', '236', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('379', '55', 'Stockpile 08 (Old Wet Plant Coarse 5)', '237', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('380', '55', 'Stockpile 09 (Old Wet Plant Fine 1)', '238', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('381', '55', 'Stockpile 10 (Old Wet Plant Fine 2)', '239', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('382', '55', 'Stockpile 11 (Old Wet Plant Fine 3)', '240', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('383', '55', 'Stockpile 12 (Old Wet Plant Fine 4)', '241', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('384', '55', 'Stockpile 13 (Old Wet Plant Fine 5)', '242', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('385', '55', 'Stockpile 14 (Dry Plant Coarse 1)', '243', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('386', '55', 'Stockpile 15 (Dry Plant Fine 1)', '244', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('387', '101', 'Wet Plant Gate 01', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('388', '101', 'Wet Plant Gate 02', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('389', '101', 'Wet Plant Gate 03', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('390', '101', 'Wet Plant Gate 04', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('391', '101', 'Wet Plant Gate 05', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('392', '101', 'Wet Plant Gate 06', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('393', '101', 'Wet Plant Gate 07', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('394', '101', 'Wet Plant Gate 08', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('395', '101', 'Stockpile 01 (Wet Plant Coarse 1)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('396', '101', 'Stockpile 04 (Old Wet Plant Coarse 1)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('397', '101', 'Stockpile 05 (Old Wet Plant Coarse 2)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('398', '101', 'Stockpile 06 (Old Wet Plant Coarse 3)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('399', '101', 'Stockpile 07 (Old Wet Plant Coarse 4)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('400', '101', 'Stockpile 08 (Old Wet Plant Coarse 5)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('401', '101', 'Stockpile 14 (Dry Plant Coarse 1)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('402', '102', 'Wet Plant Gate 01', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('403', '102', 'Wet Plant Gate 02', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('404', '102', 'Wet Plant Gate 03', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('405', '102', 'Wet Plant Gate 04', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('406', '102', 'Wet Plant Gate 05', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('407', '102', 'Wet Plant Gate 06', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('408', '102', 'Wet Plant Gate 07', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('409', '102', 'Wet Plant Gate 08', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('410', '102', 'Stockpile 01 (Wet Plant Coarse 1)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('411', '102', 'Stockpile 04 (Old Wet Plant Coarse 1)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('412', '102', 'Stockpile 05 (Old Wet Plant Coarse 2)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('413', '102', 'Stockpile 06 (Old Wet Plant Coarse 3)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('414', '102', 'Stockpile 07 (Old Wet Plant Coarse 4)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('415', '102', 'Stockpile 08 (Old Wet Plant Coarse 5)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('416', '102', 'Stockpile 14 (Dry Plant Coarse 1)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('417', '103', 'Wet Plant Gate 01', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('418', '103', 'Wet Plant Gate 02', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('419', '103', 'Wet Plant Gate 03', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('420', '103', 'Wet Plant Gate 04', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('421', '103', 'Wet Plant Gate 05', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('422', '103', 'Wet Plant Gate 06', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('423', '103', 'Wet Plant Gate 07', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('424', '103', 'Wet Plant Gate 08', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('425', '103', 'Stockpile 01 (Wet Plant Coarse 1)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('426', '103', 'Stockpile 04 (Old Wet Plant Coarse 1)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('427', '103', 'Stockpile 05 (Old Wet Plant Coarse 2)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('428', '103', 'Stockpile 06 (Old Wet Plant Coarse 3)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('429', '103', 'Stockpile 07 (Old Wet Plant Coarse 4)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('430', '103', 'Stockpile 08 (Old Wet Plant Coarse 5)', '0', '1');
INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('431', '103', 'Stockpile 14 (Dry Plant Coarse 1)', '0', '1');

# ADD AUTO_INCREMENT to id column, then set auto_increment to start at 432 (431 is last ID in legacy data) on the table
set session sql_mode='NO_AUTO_VALUE_ON_ZERO';
ALTER TABLE `gb_qc_locations_details` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `gb_qc_locations_details` AUTO_INCREMENT = 432;
set session sql_mode='';

# Test insert to check the auto-increment
# INSERT INTO `gb_qc_locations_details` (`id`, `qc_location_id`, `description`, `sort_order`, `is_active`) VALUES ('0', '0', 'NA', '0', '1');

# ADD CONSTRAINTS, FOREIGN KEYS, INDEXES, ETC.

