
/*******************************************************************************************************************************************
 * File Name: prod_tickets.sql
 * Project: silicore
 * Description:
 * Notes:
 * =========================================================================================================================================
 * Change Log ([MM/DD/YYYY]|[Developer]|[Task Ticket] - [Description])
 * =========================================================================================================================================
 * 11/10/2017|whildebrandt|KACE:16787 - Initial creation
 *
 ******************************************************************************************************************************************/

DROP TABLE IF EXISTS `prod_tickets`;

CREATE TABLE `prod_tickets` (
  `ticket_no` varchar(15) NOT NULL DEFAULT '0' COMMENT 'BOL #, required',
  `load_id` int(11) DEFAULT NULL,
  `rail_car_release_id` bigint(20) DEFAULT NULL,
  `invoice_id` bigint(20) DEFAULT NULL,
  `invoice_credit_id` bigint(20) DEFAULT NULL,
  `arrival_dt` datetime DEFAULT NULL,
  `date` date DEFAULT NULL,
  `time` time DEFAULT NULL,
  `dt` datetime NOT NULL,
  `dt_short` bigint(11) NOT NULL,
  `shift_date` date DEFAULT NULL,
  `shift` varchar(5) DEFAULT NULL,
  `departure_dt` datetime DEFAULT NULL,
  `customer_id` bigint(20) DEFAULT NULL,
  `customer` varchar(64) DEFAULT NULL,
  `po_id` bigint(20) DEFAULT NULL,
  `job` varchar(128) DEFAULT NULL,
  `po_no_old` varchar(64) DEFAULT NULL,
  `destination` varchar(96) DEFAULT NULL,
  `product_id` int(11) NOT NULL,
  `customer_product_id` bigint(20) DEFAULT NULL,
  `site_id` int(11) DEFAULT NULL,
  `silo_id` int(11) NOT NULL,
  `silo_no` varchar(6) DEFAULT NULL,
  `scale_id_gross` int(11) DEFAULT NULL,
  `scale_id_tare` int(11) DEFAULT NULL,
  `inventory_silo_id` bigint(20) DEFAULT NULL,
  `carrier_id` bigint(20) DEFAULT NULL,
  `carrier` varchar(50) DEFAULT NULL,
  `vehicle_no` varchar(10) DEFAULT NULL,
  `driver_id` bigint(20) DEFAULT NULL,
  `driver_user_id` bigint(20) DEFAULT NULL,
  `transfer_site_id` int(11) DEFAULT NULL,
  `transfer_dt` datetime DEFAULT NULL,
  `transfer_from_rail_car_id` varchar(20) DEFAULT NULL,
  `transfer_from_rail_car_net_pounds` int(11) DEFAULT NULL,
  `transfer_from_rail_car_net_tons` decimal(10,2) DEFAULT NULL,
  `transfer_from_rail_car_2_id` varchar(20) DEFAULT NULL,
  `transfer_from_rail_car_2_net_pounds` int(11) DEFAULT NULL,
  `transfer_from_rail_car_2_net_tons` decimal(10,2) DEFAULT NULL,
  `transfer_from_silo_id` int(11) DEFAULT NULL,
  `transfer_to_rail_car_id` varchar(20) DEFAULT NULL,
  `transfer_to_silo_id` int(11) DEFAULT NULL,
  `gross_pounds` int(11) DEFAULT NULL,
  `tare_pounds` int(11) DEFAULT NULL,
  `net_pounds` int(11) DEFAULT NULL,
  `net_tons` decimal(10,2) DEFAULT NULL,
  `carrier_ticket_no` varchar(20) DEFAULT NULL,
  `pounds_received` int(11) DEFAULT NULL,
  `tons_received` decimal(10,2) DEFAULT NULL,
  `received_site_id` int(11) DEFAULT NULL,
  `received_silo_id` int(11) DEFAULT NULL,
  `received_by` varchar(8) DEFAULT NULL,
  `ticket_manual_img_path` varchar(50) DEFAULT NULL,
  `ticket_img_path` varchar(50) DEFAULT NULL,
  `vehicle_img_path` varchar(50) DEFAULT NULL,
  `ok_status_code` varchar(1) DEFAULT NULL,
  `void_status_code` varchar(1) NOT NULL DEFAULT 'A',
  `void_reason_code` varchar(1) NOT NULL DEFAULT 'A',
  `void_comments` varchar(100) DEFAULT NULL,
  `void_email_dt` datetime DEFAULT NULL,
  `sent_dt` datetime DEFAULT NULL,
  `stored_vehicle_pu_dt` datetime DEFAULT NULL,
  `stored_vehicle_pu_user_id` bigint(20) DEFAULT NULL,
  `duplicate_email_dt` datetime DEFAULT NULL,
  `constraint_override_dt` datetime DEFAULT NULL,
  `constraint_override_user_id` bigint(20) DEFAULT NULL,
  `weighmaster_error_status_code` varchar(1) DEFAULT NULL,
  `jws_user_id` bigint(20) DEFAULT NULL,
  `jws_is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `is_ok_for_billing` varchar(1) NOT NULL DEFAULT 'Y',
  `create_dt` datetime DEFAULT NULL,
  `create_user_id` bigint(20) DEFAULT NULL,
  `edit_dt` datetime DEFAULT NULL,
  `edit_user_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ticket_no`),
  KEY `date` (`date`),
  KEY `dt_short` (`dt_short`),
  KEY `po_id` (`po_id`),
  KEY `void_status_code` (`void_status_code`),
  KEY `void_reason_code` (`void_reason_code`),
  KEY `carrier_id` (`carrier_id`),
  KEY `site_id` (`site_id`),
  KEY `inventory_silo_id` (`inventory_silo_id`),
  KEY `load_id` (`load_id`),
  KEY `customer_id` (`customer_id`),
  KEY `silo_id` (`silo_id`),
  KEY `dt` (`dt`),
  KEY `driver_id` (`driver_id`),
  KEY `transfer_site_id` (`transfer_site_id`),
  KEY `invoice_id` (`invoice_id`),
  KEY `product_id` (`product_id`),
  KEY `received_silo_id` (`received_silo_id`),
  KEY `received_site_id` (`received_site_id`),
  KEY `invoice_credit_id` (`invoice_credit_id`),
  KEY `rail_car_release_id` (`rail_car_release_id`),
  KEY `driver_user_id` (`driver_user_id`),
  KEY `ok_status_code` (`ok_status_code`),
  KEY `customer_product_id` (`customer_product_id`),
  KEY `transfer_to_rail_car_id` (`transfer_to_rail_car_id`),
  KEY `transfer_to_silo_id` (`transfer_to_silo_id`),
  KEY `transfer_from_rail_car_id` (`transfer_from_rail_car_id`),
  KEY `transfer_from_rail_car_2_id` (`transfer_from_rail_car_2_id`),
  CONSTRAINT `prod_tickets_ibfk_1` FOREIGN KEY (`carrier_id`) REFERENCES `prod_carriers` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `prod_tickets_ibfk_10` FOREIGN KEY (`transfer_to_silo_id`) REFERENCES `prod_silos` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `prod_tickets_ibfk_11` FOREIGN KEY (`customer_id`) REFERENCES `prod_customers` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `prod_tickets_ibfk_12` FOREIGN KEY (`customer_product_id`) REFERENCES `prod_products_customers` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `prod_tickets_ibfk_14` FOREIGN KEY (`inventory_silo_id`) REFERENCES `prod_inventory_silos` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `prod_tickets_ibfk_15` FOREIGN KEY (`invoice_credit_id`) REFERENCES `prod_invoices` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `prod_tickets_ibfk_16` FOREIGN KEY (`invoice_id`) REFERENCES `prod_invoices` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `prod_tickets_ibfk_17` FOREIGN KEY (`load_id`) REFERENCES `prod_dispatch_loads` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `prod_tickets_ibfk_18` FOREIGN KEY (`po_id`) REFERENCES `prod_purchase_orders` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `prod_tickets_ibfk_2` FOREIGN KEY (`product_id`) REFERENCES `prod_products_final` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `prod_tickets_ibfk_3` FOREIGN KEY (`rail_car_release_id`) REFERENCES `prod_rail_car_releases` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `prod_tickets_ibfk_4` FOREIGN KEY (`received_silo_id`) REFERENCES `prod_silos` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `prod_tickets_ibfk_5` FOREIGN KEY (`received_site_id`) REFERENCES `prod_sites` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `prod_tickets_ibfk_6` FOREIGN KEY (`silo_id`) REFERENCES `prod_silos` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `prod_tickets_ibfk_7` FOREIGN KEY (`site_id`) REFERENCES `prod_sites` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `prod_tickets_ibfk_8` FOREIGN KEY (`transfer_site_id`) REFERENCES `prod_sites` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



